/* The share cards' fonts (spec 8.7.5). Passing fonts to ImageResponse
   replaces next/og's own, so the cards carry their text font too.

   - Text: Geist Regular 1.800, Latin (U+0020-017F) and its punctuation, cut
     from the copy next/og ships (next/dist/compiled/@vercel/og). Copyright
     2024 The Geist Project Authors (https://github.com/vercel/geist-font).
   - Glyphs: the Moon, Mercury, Venus, Mars, Jupiter, Saturn and the 12
     signs from Noto Sans Symbols 2.003, and the Sun from Noto Sans Symbols 2
     2.008 (notofonts.github.io, fonts/NotoSansSymbols/hinted/ttf/ and
     fonts/NotoSansSymbols2/hinted/ttf/, downloaded 4 Oct 2026). Copyright
     2022 The Noto Project Authors (https://github.com/notofonts/symbols).
     Merged, renamed "Retrospect Card Symbols", and moved to Private Use
     code points U+E000 to U+E012 in `glyphs.ts`'s order (`cardGlyph`).

   Why Private Use: Satori, which draws these cards, ignores U+FE0E. It
   sends Taurus as text (U+2649 U+FE0E) to its emoji loader as
   "2649-fe0e", which asks twemoji for a file that doesn't exist, so every
   sign would draw blank; and it asks Google Fonts for a glyph for the
   selector itself beside the planets. Measured 4 Oct 2026, next 16 (see
   the 3d write-up). At Private Use code points the glyphs are only ever
   text, drawn from this font, with nothing fetched.

   Both are licensed under the SIL Open Font License, Version 1.1
   (https://openfontlicense.org); each font's name table, which the cut
   keeps, carries the notice. Cut with fontTools 4.57.0 (pyftsubset
   --no-hinting --name-IDs='*' --name-languages='*'):

     text:   --unicodes="U+0020-007E,U+00A0-00FF,U+0100-017F,U+2010-2027,U+2030-203A,U+2122,U+2190-2193,U+2212" --layout-features='kern,liga'
     glyphs: --unicodes="U+263D,U+263F,U+2640,U+2642-2644,U+2648-2653" and, from Symbols 2, "U+2609",
             --layout-features='', then fontTools.merge and the cmap moved to U+E000.

   30,604 and 5,000 bytes. A character the text font lacks (a
   song title in another script) is left to Satori, which asks Google Fonts
   for it. `cardFonts.test.ts` reads both character maps. */

const TEXT =
  "AAEAAAAOAIAAAwBgR0RFRg1OB4sAAFJkAAAAdkdQT1PgHdlqAABS3AAAI+hHU1VCM2I2dQAAdsQAAADGT1MvMlV0BekAAEoAAAAAYGNtYXCxgDMPAABKYAAAA0hnYXNwAAAAEAAAUlwAAAAIZ2x5Zp" +
  "ftrpEAAADsAAA/9GhlYWQy9G9tAABD5AAAADZoaGVhDEoK1QAASdwAAAAkaG10eAlYRtIAAEQcAAAFwGxvY2Fg7FEmAABBAAAAAuJtYXhwAYoAzwAAQOAAAAAgbmFtZW9SkhcAAE2oAAAEknBvc3T/" +
  "nwAyAABSPAAAACAAAgAUAAACiALGAAcACgAAMwEzASMnIQcTMwMUAQB0AQBeR/7WR2TweALG/TrKygEeAV0A//8AFAAAAogDigImAAEAAAAHAVcA/QC0//8AFAAAAogDjwImAAEAAAAHAVsAlgC0//" +
  "8AFAAAAogDjwImAAEAAAAHAVkAmQC0//8AFAAAAogDewImAAEAAAAHAVQAnwC0//8AFAAAAogDigImAAEAAAAHAVYAqQC0//8AFAAAAogDbQImAAEAAAAHAV4AnAC0//8AFP8uAqsCxgImAAEAAAAH" +
  "AWIBzAAA//8AEwAAAocDrAAmAAH/AAAHAVwAwgC0//8AFAAAAogDjgImAAEAAAAHAV0AhAC0AAIAFAAAA5MCxgAPABMAADMBIRUhFSEVIRUhFSE1IQcBIwMzFAF8Afv+uAE8/sQBUP5a/vBoAXgzse" +
  "QCxlTlUudUysoCdf6pAAMAXAAAAmoCxgAOABYAHwAAMxEzMhYVFAYHFhYVFAYjAzMyNjU0IyMRMzI2NTQmIyNc9H5+QztJU350xp5OVKKexklPT0nGAsZcYzxRCwpdRWFiAZM7NW/94jw4OD8AAAEA" +
  "Lf/wApcC1gAeAAAFIiYmNTQ2NjMyFhcHJiYjIgYGFRQWFjMyNjcXDgIBbF+QUFCQX4GOFlsPYllEZzo6Z0RdZg1bDUx9EFmmc3OnWoJwBkxYRYFaWoBEYVMGTXRB//8ALf/wApcDigImAA0AAAAHAV" +
  "cBGQC0//8ALf/wApcDjwImAA0AAAAHAVoAtQC0//8ALf8kApcC1gImAA0AAAAHAWEAwwAA//8ALf/wApcDjwImAA0AAAAHAVkAtQC0//8ALf/wApcDewImAA0AAAAHAVUBEgC0AAIAXAAAAo0CxgAI" +
  "AA8AADMRMzIWFRQGIyczMhEQIyNc3KSxrqGMhvv7hgLGuauquFQBDgEQ//8AXAAAAo0DjwImABMAAAAHAVoAjgC0//8AFAAAAo0CxgImABMAAAAGAWeYB///ABQAAAKNAsYCJgATAAAABgFnmAcAAQ" +
  "BcAAACIgLGAAsAADMRIRUhFSEVIRUhFVwBvv6YAVz+pAFwAsZU5VLnVP//AFwAAAIiA4oCJgAXAAAABwFXAOwAtP//AFwAAAIiA48CJgAXAAAABwFaAIgAtP//AFwAAAIiA48CJgAXAAAABwFZAIgA" +
  "tP//AFwAAAIiA3sCJgAXAAAABwFUAI4AtP//AFwAAAIiA3sCJgAXAAAABwFVAOUAtP//AFwAAAIiA4oCJgAXAAAABwFWAJgAtP//AFwAAAIiA20CJgAXAAAABwFeAIsAtP//AFz/LgJFAsYCJgAXAA" +
  "AABwFiAWYAAAABAFwAAAIaAsYACQAAMxEhFSEVIRUhEVwBvv6YAVb+qgLGVO5S/s4AAQAt//ACigLWACQAAAUiJiY1NDY2MzIWFhcHJiYjIgYGFRQWFjMyNjY3IzUhESMnBgYBamSOS0yPZFV1RQ1a" +
  "DVpbUWUvMGZPP1wyAcwBHEAEG3gQYKdra6hhPmpCBkVXUINNUYFMOWA4Uv6ZdzxL//8ALf/wAooDjwImACEAAAAHAVsAtAC0//8ALf/wAooDjwImACEAAAAHAVkAtwC0//8ALf8QAooC1gImACEAAA" +
  "AHAWAA/QAA//8ALf/wAooDewImACEAAAAHAVUBFAC0AAEAXAAAAm0CxgALAAAzETMRIREzESMRIRFcVgFlVlb+mwLG/skBN/06ATv+xf//ABEAAAK5AsYCJgAmAAAABgFk/f3//wBcAAACbQOPAiYA" +
  "JgAAAAcBWQCwALQAAQBcAAAAsgLGAAMAADMRMxFcVgLG/Tr//wBc//ADAgLGACYAKQAAAAcAMwD6AAD//wBcAAABAgOKAiYAKQAAAAcBVwA2ALT////+AAABEAOPAiYAKQAAAAcBWf/SALT//wAEAA" +
  "ABCgN7AiYAKQAAAAcBVP/YALT//wBbAAAAswN7AiYAKQAAAAcBVQAvALT//wAOAAAAsgOKAiYAKQAAAAcBVv/iALT//wABAAABDQNtAiYAKQAAAAcBXv/VALT//wAi/y4A1QLGAiYAKQAAAAYBYvYA" +
  "////6QAAASQDjgImACkAAAAHAV3/vQC0AAEAQ//wAggCxgARAAAFIiYmJzcWFjMyNjURMxEUBgYBJUJmOQFYAUhBRElWOGUQP3BJBlJYXlYBzv4yUXdAAP//AEP/8AJnA48CJgAzAAAABwFZASkAtA" +
  "ABAFwAAAJxAsYACwAAMxEzEQEzAQEjAwcVXFYBP23+6gEpafpcAsb+nwFh/sz+bgFSZe3//wBc/xACcQLGAiYANQAAAAcBYADqAAAAAQBcAAACFQLGAAUAADMRMxEhFVxWAWMCxv2OVAD//wBcAAAC" +
  "FQOKAiYANwAAAAcBVwA2ALT//wBcAAACFQLGAiYANwAAAAcBWAFeAAD//wBc/xACFQLGAiYANwAAAAcBYADIAAD//wAUAAACFQLGAiYANwAAAAYBaOzvAAEAXAAAAxECxgAMAAAzETMTEzMRIxEDIw" +
  "MRXHjj4nhWy3PLAsb9mAJo/ToCJv3aAib92gABAFwAAAKLAsYACQAAMxEzAREzESMBEVx6AV9WgP6nAsb9kAJw/ToCZP2c//8AXAAAAosDigImAD0AAAAHAVcBMQC0//8AXAAAAosDjwImAD0AAAAH" +
  "AVoAzQC0//8AXP8QAosCxgImAD0AAAAHAWABBAAA//8AXAAAAosDjgImAD0AAAAHAV0AuAC0AAEAXP9qAosCxgATAAAzETMBETMRFAYjIzUzMjY1NSMBEVx6AV9WUUVnaCAfKv6nAsb9kQJv/TNBTl" +
  "AiHAgCY/2dAAIALf/wArYC1gAPABsAAAUiJiY1NDY2MzIWFhUUBgYnMjY1NCYjIgYVFBYBcWWRTk6RZWaRTk6RZm59fW5tfX0QWaZzc6daWqdzc6ZZVJeHh5mZh4eXAP//AC3/8AK2A4oCJgBDAAAA" +
  "BwFXASAAtP//AC3/8AK2A48CJgBDAAAABwFZALwAtP//AC3/8AK2A3sCJgBDAAAABwFUAMIAtP//AC3/8AK2A4oCJgBDAAAABwFWAMwAtP//AC3/8AK2A4oCJgBDAAAAJwFXAN0AtAAHAVcBYAC0//" +
  "8ALf/wArYDbQImAEMAAAAHAV4AvwC0//8ALf/wArYC1gImAEMAAAAGAWkjAP//AC3/8AK2A44CJgBDAAAABwFdAKcAtAACAC3/8AQHAtYAGgAqAAAFIiYmNTQ2NjMyFhc1IRUhFSEVIRUhFSE1BgYn" +
  "MjY2NTQmJiMiBgYVFBYWAXBnkExLkWdQeCcBoP62AT7+wgFS/lgneFBPaDU0aU9OaDM0ZxBep21up189OGVU5VLnVGQ3PVRJgVRTgktLglNUgUkAAAIAXAAAAlYCxgAKABEAADMRMzIWFRQGIyMRET" +
  "MyNTQjI1z/d4SEd6mpoaGpAsZyZWd0/uwBaIeDAAACAFwAAAI4AsYADAATAAAzETMVMzIWFRQGIyMVEyMRMzI1NFxWineFhXeKioqKogLGgHJmZnKWAfL++ISEAAIALf+7ArAC1gAUACgAAAUnBgYj" +
  "IiYmNTQ2NjMyFhYVFAYHFyUyNjcnMxc2NTQmJiMiBgYVFBYWAiQ7GEAjZo9MS5BmaJBKRkJY/u4WIg1nXExiM2dOTmYzM2dFTAoNY6hnaKhkZKhoYqQyb4kFBoFkTqhPgk9Pgk9Ogk4AAAIAXAAAAm" +
  "ICxgAUAB0AADMRITIWFRQGBgcWFhcXIycmJiMjEREzMjY1NCYjI1wBDXCCIjYgLzcFFFcSBDc+zsJBTE5KtwLGdGMpQy4JCDw30cgsKv7iAXJCPT5DAP//AFwAAAJiA4oCJgBQAAAABwFXAQAAtP//" +
  "AFwAAAJiA48CJgBQAAAABwFaAJwAtP//AFz/EAJiAsYCJgBQAAAABwFgAO0AAAABADf/8AJJAtYALQAABSImJic3FhYzMjY1NCYmJy4CNTQ2NjMyFhYXByYmIyIGFRQWFhceAhUUBgYBUFJ6RwZaC2" +
  "FVSlMfV1VSYSs5aklOcEIIWglXUEJOH1BLWWktQHAQPm1IBk9WOTchMysVFTJINTxbMztmQQZBUz8zISshExY9UDM+WzH//wA3//ACSQOKAiYAVAAAAAcBVwDhALT//wA3//ACSQOPAiYAVAAAAAcB" +
  "WgB9ALT//wA3/yQCSQLWAiYAVAAAAAcBYQCcAAD//wA3//ACSQOPAiYAVAAAAAcBWQB9ALQAAQAMAAACHALGAAcAADMRIzUhFSMR6d0CEN0CclRU/Y4A//8ADAAAAhwCxgImAFkAAAAGAWfkAP//AA" +
  "wAAAIcA48CJgBZAAAABwFaAF8AtP//AAz/JAIcAsYCJgBZAAAABgFhaQAAAQBN//ACZALGABMAAAUiJiY1ETMRFBYzMjY1ETMRFAYGAVlSeUFWX1dWX1ZBeBBAd1EBzv4yVl5eVgHO/jJRd0D//wBN" +
  "//ACZAOKAiYAXQAAAAcBVwEIALT//wBN//ACZAOPAiYAXQAAAAcBWwChALT//wBN//ACZAOPAiYAXQAAAAcBWQCkALT//wBN//ACZAN7AiYAXQAAAAcBVACqALT//wBN//ACZAOKAiYAXQAAAAcBVg" +
  "C0ALT//wBN//ACZAOKAiYAXQAAACcBVwDFALQABwFXAUgAtP//AE3/8AJkA20CJgBdAAAABwFeAKcAtP//AE3/MQJkAsYCJgBdAAAABwFiAQ0AA///AE3/8AJkA6wCJgBdAAAABwFcANEAtP//AE3/" +
  "8AJkA44CJgBdAAAABwFdAI8AtAABABQAAAKHAsYABgAAIQEzExMzAQEV/v9e3Nte/v8Cxv2YAmj9OgAAAQAmAAADiwLGAAwAADMDMxMTMxMTMwMjAwPhu16SkWKSkV+7bIyMAsb9sAJQ/bACUP06Ai" +
  "b92v//ACYAAAOLA48CJgBpAAAABwFZASMAtAABAA8AAAJPAsYACwAAMxMDMxMTMwMTIwMDD+nnZrm3ZOfrZru7AWQBYv7iAR7+oP6aASL+3gAB//oAAAJGAsYACAAAMxEDMxMTMwMR9ftmwMBm+wEi" +
  "AaT+tAFM/lz+3v////oAAAJGA4oCJgBsAAAABwFXAM8AtP////oAAAJGA48CJgBsAAAABwFZAGsAtP////oAAAJGA3sCJgBsAAAABwFUAHEAtAABABwAAAIEAsYACQAAMzUBITUhFQEhFRwBfP6RAd" +
  "H+hAGGWAIaVFj95lQA//8AHAAAAgQDigImAHAAAAAHAVcAxwC0//8AHAAAAgQDjwImAHAAAAAHAVoAYwC0//8AHAAAAgQDewImAHAAAAAHAVUAwAC0AAIALP/0AhQCHgAgACsAABciJjU0Njc3NCMi" +
  "BgcnNjYzMhYVFRQzMxUGIyImJycGBicyNjU1BwYGFRQW31JhUFe8fjdADFkPc1pmbBwVDBQuLwYBFGIzUFisNik1DExERE4QI4UxLgdLXXNl2yFKAiUqBSk1SlpCJiAKKSElKQD//wAs//QCFALWAi" +
  "YAdAAAAAcBVwDFAAD//wAs//QCFALbAiYAdAAAAAYBW14A//8ALP/0AhQC2wImAHQAAAAGAVlhAP//ACz/9AIUAscCJgB0AAAABgFUZwD//wAs//QCFALWAiYAdAAAAAYBVnEA//8ALP/0AhQCuQIm" +
  "AHQAAAAGAV5kAP//ACz/LgI3Ah4CJgB0AAAABwFiAVgAAP//ACz/9AIUAvgCJgB0AAAABwFcAI4AAP//ACz/9AIUAtoCJgB0AAAABgFdTAAAAwAs//QDawIeACwAMwA+AAAXIiY1NDY2NzcmJiMiBg" +
  "cnNjYzMhc2NjMyFhYVFSEWFjMyNjcXBgYjIiYnBgYTISYmIyIGAzY2NTUHBgYVFBbhT2YvTSu8ATxENz8KWRByV4Q0H189RWo7/n8FUUU0Qw1aFXVUSGoeG2+/ASUGTTs9T/5BV6w8IzkMSUc4QiIG" +
  "GUpFNikHTFxcLDBBfFkZVVYxKAdHWz85N0EBRU1IS/67A1BJHBYHLx0nKwACAFD/9AInAsYAEgAeAAAFIiYnByMRMxU2NjMyFhYVFAYGJzI2NTQmIyIGFRQWAUM3VhcDTFQUVDdGZjg4ZktDTk5BSV" +
  "NSDDErUALG/iE1RHxVVXxEUGpbXGlpXFtqAAABACz/9AIAAh4AGwAABSImJjU0NjYzMhYXByYmIyIGFRQWMzI2NxcGBgEfSm08PG1KXHgNWAlKNklSUkk2SglYDXgMRH1UVHxFX1kGNTlpXFxpPDwG" +
  "WGr//wAs//QCAALWAiYAgAAAAAcBVwDOAAD//wAs//QCAALbAiYAgAAAAAYBWmoA//8ALP8kAgACHgImAIAAAAAGAWF0AP//ACz/9AIAAtsCJgCAAAAABgFZagD//wAs//QCAALHAiYAgAAAAAcBVQ" +
  "DHAAAAAgAs//QCAwLGABIAHgAABSImJjU0NjYzMhYXNTMRIycGBicyNjU0JiMiBhUUFgEMRWU2NmVFNVgWVEwDFlonR0tLR0ZTUwxEfFVVfEQtKf79OlArMVBqW1xpaVxbagD//wAs//QCqgLGACYA" +
  "hgAAAAcBWAIGAAD//wAs//QCRQLGAiYAhgAAAAcBYwCdAQoAAgAs//QCIQLSAB4AKgAABSImJjU0NjYzMhYXJicHJzcmJzcWFhc3FwcWFhUUBicyNjU0JiMiBhUUFgEfSW48PG5JKEQdFit4GEw1SR" +
  "Q+YiWLGG0yK4RuSVFRSUlSUgw+dE9Qcz4aFkYsKkAbGQZKBiYdMUAmP69nf4xQXV5NWlxVVVwAAgAs//QCBQIeABcAHgAABSImJjU0NjYzMhYWFRUhFhYzMjY3FwYGAyEmJiMiBgEfS207O2tJRWo7" +
  "/n8FUUU0Qw1aFXXvASUGTTs9TwxEfVRUfEVBfFkZVVYxKAdHWwFFTUhL//8ALP/0AgUC1AImAIoAAAAHAVcAzv/+//8ALP/0AgUC2QImAIoAAAAGAVpq/v//ACz/9AIFAtkCJgCKAAAABgFZav7//w" +
  "As//QCBQLFAiYAigAAAAYBVHD+//8ALP/0AgUCxQImAIoAAAAHAVUAx//+//8ALP/0AgUC1AImAIoAAAAGAVZ6/v//ACz/9AIFArcCJgCKAAAABgFebf4AAgAs/y4CBQIeAC0ANAAABSImJjU0NjYz" +
  "MhYWFRUhFhYzMjY3FwYHMwcGBhUUFjMyNxcGBiMiJjU0Njc3BgMhJiYjIgYBH0ttOztrSUVqO/5/BVFFNEMNWg4fA1MTEBANHBQYCzEaKzAZFgYTrwElBk07PU8MRH1UVHxFQXxZGVVWMSgHLyVlGC" +
  "QPEBAOOAsPLScgNRkHAwFFTUhLAAABADwAAAFkAsYAEwAAMxEjNTM1NDYzMxUjIgYVFTMVIxGESEhESFROHx+FhQHISjA7SUoiHipK/jgAAgAs/14CAgIeAB4AKgAABSImJzcWFjMyNjU1BgYjIiYm" +
  "NTQ2NjMyFhc1MxEUBgMyNjc2JiMiBhUUFgEZVXgRWAw9PUhNE1Q0Q2k7OmdCOFkSUHtwRFIBAlRFRk1PolRGBiUrOjpWKjJCdEtMc0I0LFT+El1pAQ5fUlJfX1JSX///ACz/XgICAtsCJgCUAAAABg" +
  "FbYwD//wAs/14CAgLbAiYAlAAAAAYBWWYA//8ALP9eAgIDFgImAJQAAAAHAV8AuwAA//8ALP9eAgICxwImAJQAAAAHAVUAwwAAAAEAUAAAAfUCxgASAAAzETMRNjYzMhYVESMRNCMiBhURUFQVVDdW" +
  "W1RvQE4Cxv75MS5wWf6rAT2XTkr+xAD//wAKAAAB9QLGAiYAmQAAAAcBY/+OAQr////xAAAB9QN7AiYAmQAAAAcBWf/FAKD//wBOAAAApgLHAiYAnQAAAAYBVSIAAAEAUAAAAKQCEgADAAAzETMRUF" +
  "QCEv3u//8AUAAAAPUC1gImAJ0AAAAGAVcpAP////EAAAEDAtsCJgCdAAAABgFZxQD//wAOAAAA5gLHAiYAnQAAAAYBauIA//8AAQAAAKQC1gImAJ0AAAAGAVbVAP////QAAAEAArkCJgCdAAAABgFe" +
  "yAD//wAU/y4AxwLHAiYAnQAAACYBVSIAAAYBYugA////3AAAARcC2gImAJ0AAAAGAV2wAP//AE7/agGgAscAJgCdAAAAJgFVIgAAJwCnAOoAAAAHAVUBHAAA////+/9qALYCxwImAKcAAAAGAVUyAA" +
  "AB//v/agC0AhIACwAABzUzMjY1ETMRFAYjBSsaIFQ+SJZKGSECJP3YRjoA////+/9qARMC2wImAKcAAAAGAVnVAAABAFAAAAIfAsYACwAAMxEzEQEzBxMjJwcVUFQBAnDR2mataALG/i8BHeH+z/hu" +
  "iv//AFD/EAIfAsYCJgCpAAAABwFgALYAAAABAFAAAADzAsYACgAAMyImNREzERQzMxW4LjpUIS4wNAJi/aUhSgD//wBQAAAA9QNiAiYAqwAAAAcBVwApAIz//wBQAAABUgLGACYAqwAAAAcBWACuAA" +
  "D//wBQ/xAA8wLGAiYAqwAAAAYBYDQA//8ABgAAAPMCxgImAKsAAAAGAWXeEAABAFAAAAMdAh4AIQAAMxEzFzY2MzIWFzY2MzIWFREjETQjIgYVESMRNCYjIgYVEVBNAhROMzxSERFQOlVaVG83Q1Qy" +
  "OzdEAhJdMTg6NTU6aWD+qwFDkVBH/sMBPUdQUEf+wwAAAQBQAAAB9QIeABQAADMRMxc2NjMyFhYVESMRNCYjIgYVEVBNAhVXNz1PJ1Q1PD1PAhJfNzQ2Wzj+qwE9Sk1NSv7DAP//AFAAAAH1AtYCJg" +
  "CxAAAABwFXANIAAP//AFAAAAH1AtsCJgCxAAAABgFabgD//wBQ/xAB9QIeAiYAsQAAAAcBYACyAAD//wBQAAAB9QLaAiYAsQAAAAYBXVkAAAEAUP9qAfUCHgAcAAAzETMXNjYzMhYWFREUBiMjNTMy" +
  "NjURNCYjIgYVEVBNAhVXNz1PJ1FFUVMdIzU8PU8CEl83NDZbOP6kQU5KJR8BRUpNTUr+wwAAAgAs//QCEQIeAA8AGwAABSImJjU0NjYzMhYWFRQGBicyNjU0JiMiBhUUFgEfSW48PG5JSW08PG1JSV" +
  "FRSUlSUgxEfVRVfEREfFVUfURQaVxcaWlcXGkA//8ALP/0AhEC1gImALcAAAAHAVcAzgAA//8ALP/0AhEC2wImALcAAAAGAVlqAP//ACz/9AIRAscCJgC3AAAABgFUcAD//wAs//QCEQLWAiYAtwAA" +
  "AAYBVnoA//8ALP/0AhEC1gImALcAAAAnAVcAiwAAAAcBVwEOAAD//wAs//QCEQK5AiYAtwAAAAYBXm0A//8ALP/yAhECIAImALcAAAAGAWYWAv//ACz/9AIRAtoCJgC3AAAABgFdVQD//wAs//QDkg" +
  "IeACYAtwAAAAcAigGNAAAAAgBQ/2oCJwIeABIAHgAAFxEzFzY2MzIWFhUUBgYjIiYnFTcyNjU0JiMiBhUUFlBOARhVNk9lMTFlTzRVFZZFUFBFRVFQlgKoUS4vTn5JSX5OLCbc2mhdXWhjYmFkAAIA" +
  "UP9qAicCxgARACEAABcRMxU2MzIWFhUUBgYjIiYnFTcyNjY1NCYmIyIGBhUUFhZQVi5zTWMwMGNNOVAYkDdDHx9DNzZEHx9ElgNc909OfklJfk4oJNbaOFsyNVs5Ols0MVs5AAIALP9qAgMCHgASAB" +
  "4AAAUjNQYGIyImJjU0NjYzMhYXNzMDMjY1NCYjIgYVFBYCA1QVVTRPZTExZU82VRgBTupGUFFFRVBQltwmLE5+SUl+Ti8uUf4yZGFiY2hdXWgAAAEAUAAAAU8CEgALAAAzETMXNjMzFSMiFRFQSgMb" +
  "YzQzeAISYmJQgv7A//8AUAAAAU8C1gImAMQAAAAGAVdzAP//ADsAAAFPAtsCJgDEAAAABgFaDwD//wA1/xABTwISAiYAxAAAAAYBYAkAAAEALP/0AdwCHgApAAAFIiYnNxYWMzI2NTQmJicuAjU0Nj" +
  "MyFhYXByYmIyIGFRQWFx4CFRQGARFtcgZYCD9GNjsTODZKVCJpYEZZLgVYBDdBOTYyRk5YI3EMZU4GMDkjJxUcFQoOKjwqR1sxTisGJjosIiclDA0oOypJUf//ACz/9AHcAtYCJgDIAAAABwFXALAA" +
  "AP//ACz/9AHcAtsCJgDIAAAABgFaTAD//wAs/yQB3AIeAiYAyAAAAAYBYV4A//8ALP/0AdwC2wImAMgAAAAGAVlMAAABAFAAAAIkAtAAJwAAMxE0NjYzMhYVFAYHFhYVFAYjIzUzMjY1NCYjIzUzMj" +
  "Y1NCYjIgYVEVA2YUFibjoxRVKEeEBAT1VYViwsPkY8PjxIAfZDYjVmUjdPERFhRV5sUD5APkZPQDUvO0lB/goAAAEANwAAAWYCjgATAAAhIiY1ESM1MzUzFTMVIxEUFjMzFQESSEVOTlSNjSAhTEJG" +
  "AUBKfHxK/sIkHEoA//8ANQAAAWYCjgImAM4AAAAGAWO5xAACADcAAAGZAvUAAwAXAAABNzMHAyImNREjNTM1MxUzFSMRFBYzMxUBJx5UNFNIRU5OVI2NICFMAijNzf3YQkYBQEp8fEr+wiQcSgD//w" +
  "A3/yQBZgKOAiYAzgAAAAYBYT8AAAEAUP/0Ae8CEgASAAAXIiY1ETMRFBYzMjY1ETMRIzUG/k9fVDc5P0hUUCwMa14BVf7CTUlRRwE8/e5WYgD//wBQ//QB7wLWAiYA0gAAAAcBVwDLAAD//wBQ//QB" +
  "7wLbAiYA0gAAAAYBW2QA//8AUP/0Ae8C2wImANIAAAAGAVlnAP//AFD/9AHvAscCJgDSAAAABgFUbQD//wBQ//QB7wLWAiYA0gAAAAYBVncA//8AUP/0Ae8C1gImANIAAAAnAVcAiAAAAAcBVwELAA" +
  "D//wBQ//QB7wK5AiYA0gAAAAYBXmoA//8AUP8uAhICEgImANIAAAAHAWIBMwAA//8AUP/0Ae8C+AImANIAAAAHAVwAlAAA//8AUP/0Ae8C2gImANIAAAAGAV1FAAABABYAAAICAhIABgAAMwMzExMz" +
  "A9fBXJqaXMECEv5EAbz97gABABYAAAMdAhIADAAAMwMzExMzExMzAyMDA7qkXHx+Wn59XKRqdnYCEv5GAbr+RgG6/e4Bk/5t//8AFgAAAx0C2wImAN4AAAAHAVkA5QAAAAEALwAAAhoCEgALAAAzEw" +
  "MzFzczAxMjJwcvw7lii4dkt8BikpMBEAECyMj+/P7y1tYAAQAW/2oCAwISABAAABc1MzI2NzcjAzMTEzMDBgYjZz0cGwcTHcJcnpdc1w88NZZKERMyAgj+RgG6/asrKP//ABb/agIDAtYCJgDhAAAA" +
  "BwFXALwAAP//ABb/agIDAtsCJgDhAAAABgFZWAD//wAW/2oCAwLHAiYA4QAAAAYBVF4AAAEAMwAAAeYCEgAJAAAzNQEhNSEVASEVMwFP/rsBof6xAVdUAXRKVP6MSgD//wAzAAAB5gLWAiYA5QAAAA" +
  "cBVwC9AAD//wAzAAAB5gLbAiYA5QAAAAYBWlkA//8AMwAAAeYCxwImAOUAAAAHAVUAtgAA//8APAAAAoQCxgAmAJMAAAAHAJMBIAAA//8APAAAAgkCxwAmAJMAAAAnAJ0BYwAAAAcBVQGFAAD//wA8" +
  "AAACagLGACYAkwAAAAcAqwF3AAD//wA3AAACkwKOACYAzgAAAAcAzgEtAAAAAgAoAXgBcwLWACIALAAAEyImNTQ2Nzc0JiMiBgcnNjYzMhYVFRQzMxUGBiMiJicnBgYnMjY1NQcGBhUUnDRAODRvIR" +
  "0cIAVWCU8/SEoSCgMQCxsnBQEMOh0nMlMaGAF4LystMwoWIiIaGAQ1OUdDfRg8AQIYIQMaIjsrJRcSBhgRJgAAAgAoAXgBewLWAAsAFwAAEyImNTQ2MzIWFRQGJzI2NTQmIyIGFRQW0k5cXE5NXFxN" +
  "KSwsKSosLAF4X1BQX2BPUF9BOjQzOzwyMzsAAAEAUP9qAe8CEgATAAAXETMRFBYzMjY1ETMRIzUGIyInFVBUNzk/SFRQLHUzJ5YCqP7CTUlRRwE8/e5WYhehAAACADL/8AJlAtYADwAbAAAFIiYmNT" +
  "Q2NjMyFhYVFAYGJzI2NTQmIyIGFRQWAUtWfkVFflZXfkVFfldcZGRcW2RkEFqmcnKnW1umc3KmWlSViYqWloqJlQAAAQAoAAABEgLGAAkAADMRIzUzMjY1MxG8lDw7L0QCDkovP/06AAABADwAAAIv" +
  "AtYAHgAAMzQ2Njc+AjU0JiMiBgcnNjYzMhYVFAYGBwYGByEVPC93ajE8HEdHS1cLWgyIc256JFVKYGMDAYlLeW44GiwyJDdFTkgGaHxyXDZPRCczaClUAAABADL/8AIzAtYAKAAABSImJzcWFjMyNj" +
  "Y1NCYjIzUzMjY1NCMiBgcnNjYzMhYVFAcWFhUUBgYBLXaABVkGWUMuTjBeTTg4P1OORkcHWgp6amx8e0VPQ3YQb1gGQTgZOTBHQlQyPXA2LwZQY2dZciYTYUREYDIAAgAeAAACNQLGAAoADQAAITUh" +
  "NQEzETMVIxUlIREBh/6XAWNcWFj+qQEBmk4B3v4oVJruAVQAAQA8//ACNQLGACAAAAUiJic3FhYzMjY1NCYjIgYHIxMhFSEHNjYzMhYWFRQGBgE4cIQIWghXQ0tYV04xUBFcLwGO/sEaG1EuR2w8QH" +
  "IQb1gGPD1VS0tYKiYBj1TWHh8/b0dHbz4AAgAy//ACKQLWAB0AKgAABSImNTQ+AjMyFhcHJiYjIgYHBzY2MzIWFhUUBgYnMjY1NCYjIgYGFRQWAS54hB1Ba09faBVaDDs7UGILARpbPUZqO0BxSEZZ" +
  "VEMwTCxXEKSYWJp1Q11LCCoyfHwHJzQ8bUlOcT1UWU9KVidIMUlfAAABABQAAAIMAsYADAAAMzQ2NjchNSEVDgIVsjxxT/5mAfhZczZu285bVE5mx9N4AAADACj/8AI0AtYAGwAnADMAAAUiJiY1ND" +
  "Y3JiY1NDY2MzIWFhUUBgcWFhUUBgYDMjY1NCYjIgYVFBYTMjY1NCYjIgYVFBYBLkx3Q0o/Lzg5ZkVFZzg4Lz9KQ3ZNQkhGRENHSEJPXVNZWFRdEDBeRUVgFhNJOThYMzNYODlJExZgRUVeMAGxOTkz" +
  "PDwzOTn+o0FDPktLPkNBAAIAKP/wAh8C1gAeACoAAAUiJic3FhYzMjY3NQYGIyImJjU0NjYzMhYWFRQOAgMyNjU0JiMiBhUUFgEMWG8UWwxANFBeCR1aOEVqPUBwR1lxNhxAaUBJXVZLSVRVEFdCBy" +
  "QodYEGLTE+cEpOcT1Sk2RZl28+AUdVTEpgXkpLWAAAAf84AAABcgLGAAMAACMBMwHIAepQ/hYCxv06//8AFAAAAvgCxwAmAP4AAAAnAPoBGgAAAAcA/wHE/r3//wAUAAACyALHACYA/gAAACcA+gEa" +
  "AAAABwEBAZL+vf//ABQAAAL6As4AJgEAAAAAJwD6AUwAAAAHAQEBxP69AAEAFAFDALYCxwAJAAATNQc1MzI2NTMRdGAYLC0xAUP+ATItKP58AAABACgBQwE0As4AHgAAEzQ2Njc3NjY1NCYjIgYHJz" +
  "Y2MzIWFRQGBwcGBhUzFSgNKiw0HRYkGCQkBUAGR0A6RDQsKR4bwAFDKj40GB0QHhwaHCMkAzlFPjIwNxcWECkUOgABABQBOwEuAs4AKAAAEyImJzcWFjMyNjU0JiMjNTMyNjU0JiMiBgcnNjYzMhYV" +
  "FAYHFhYVFAahTjwDQAIjKCUnJisZGRwiHiAfIQJABkI6P0AjIDIkUQE7Pi8DGB4hHB0jORoZFx4dFAQsPDsvIiYKDDQhNz8AAgAKAUMBNgLGAAoADQAAEzUjNTczFTMVIxUnMzW+tLg+NjawbgFDWj" +
  "P27zpalI8AAQA+ACwJIgKaAAgAABM1IQEzAQEjAT4IT/7wbwE2/slvAQ8BPE4BEP7J/skBEAAAAQA+ACwGygKaAAgAABM1IQEzAQEjAT4F9/7wbwE2/slvAQ8BPE4BEP7J/skBEAAAAQA+ACwEcgKa" +
  "AAgAABM1IQEzAQEjAT4Dn/7wbwE2/slvAQ8BPE4BEP7J/skBEAAAAQAsAAAAnQBxAAMAADM1MxUscXFxAAEALP9kAJ0AcQAGAAAXNyM1MxUHLzAzcTycnHFjqgD//wBcAAAAzQH6ACYBBzAAAAcBBw" +
  "AwAYn//wBc/2QAzQH6ACcBBwAwAYkABgEIMAD//wAsAAACDwBxACYBBwAAACcBBwC5AAAABwEHAXIAAAACADIAAACjAsYACwAPAAA3LgI1NTMVFAYGBwc1MxVTAwcGVgUHA1hxzSNiZijm5ihmYiPN" +
  "cXEAAAIAMv9eAKMCJAADAA8AABMzFSMTNTQ2NjczHgIVFTJxcREGBwM3AwcFAiRx/avmKGZiIyNiZijmAAACACwAAAIDAtYAHAAgAAA3NDY3PgI1NCYjIgYHJz4CMzIWFhUUBgcGBhUHNTMV6i00Jy" +
  "kORT1KTwhaBkBsSUFjOD1BKB1mcclIVSAYJSkeNERMSAZCZjo0XDw/TyoaOjXJcXEAAgAs/14CAwI0AAMAIAAAARUjNRMiJiY1NDY3NjY1MxQGBw4CFRQWMzI2NxcOAgFVcSRBYzg+QCkcVi00JygP" +
  "RT1KUAdaBkBsAjRxcf0qNF07P08qGjs0SFUgGCUpHjRETEgGQmY6AP//ACwA+ACdAWkCBwEHAAAA+AABACwAywEMAaQACwAANyImNTQ2MzIWFRQGnDU7OzU0PDzLPS8wPT0wLz0AAAEALAF+AYICzg" +
  "ARAAATJzcjNTMnNxc3FwczFSMXByeVNEN4eEM0QkM0RHh4RDRDAX4iZkBmImtrImZAZiJqAAAC//YAAAHjAsYAGwAfAAAzNyM3MzcjNzM3MwczNzMHMwcjBzMHIwcjNyMHEzM3IyQlUwxUIFgMWSVI" +
  "JX4lSCVSDFMgVwxYJUglfiUyfiB+xUatRsjIyMhGrUbFxcUBC60AAAEAKP+SAZ8C7gADAAAXATMBKAEnUP7ZbgNc/KQAAAEAKP+SAZ8C7gADAAAFIwEzAZ9Q/tlQbgNcAAABACwA/AF3AUsAAwAANz" +
  "UhFSwBS/xPTwABACwA/QIjAUsAAwAANzUhFSwB9/1OTgABACwA/QNfAUsAAwAANzUhFSwDM/1OTgABACz/sgIBAAAAAwAAFzUhFSwB1U5OTgABAC3/kgEDAu4ACgAAFyY1NDczBhUUFhe4i4tLf0A/" +
  "btHd3tDY1mvXbAABAA//kgDlAu4ACgAAFyM2NjU0JzMWFRRaSz9Af0uLbmzXa9bY0N7dAAABAC3/jQF2Au4AIQAABSImNTU0JiM1MjY1NTQ2MzMVJgYVFRQGBxUWFhUVFBY3FQE+T1s1MjI1W084T0" +
  "NCLi9BQ09zYExTQUdTSEBTTGBOAyo1XEtTCwEKVktcNCoCTgABAA//jQFYAu4AIQAAFyM1FjY1NTQ2NzUmJjU1NCYHNTMyFhUVFBYzFSIGFRUUBkc4UEJBLy5CQlA4UFo2MTE2WnNOAio0XEtWCgEL" +
  "U0tcNSoDTmBMU0BIU0dBU0xgAAABAFz/kgFMAu4ABwAABSMRMxUjETMBTPDwoKBuA1xG/TAAAQAP/5IA/wLuAAcAABc1MxEjNTMRD6Cg8G5GAtBG/KQA//8ALP9kAJ0AcQIGAQgAAP//ACz/ZAFCAH" +
  "EAJwEIAKUAAAAGAQgAAAACAC0ByQFDAtYABgANAAATBzMVIzU3MwczFSM1N5swM3E81zAzcTwC1pxxY6qccWOq//8ALQG5AUMCxgAnAQgApgJVAAcBCAABAlUAAQAtAckAngLWAAYAABMHMxUjNTeb" +
  "MDNxPALWnHFjqv//AC0BuQCeAsYABwEIAAECVQACACwATAHpAdwABgANAAAlIyc1NzMHBSMnNTczBwEfZ4yMZ6wBdmeMjGesTKNKo8jIo0qjyP//ACcATAHkAdwAJwEpAMUAAAAGASn7AAABACwATA" +
  "EfAdwABgAAJSMnNTczBwEfZ4yMZ6xMo0qjyAAAAQAsAEwBHwHcAAYAADc3JzMXFQcsrKxnjIxMyMijSqMAAAIALQG8AS0CxgAEAAkAABMnNTMDMwMzFQdBFFgGXAZYFAG8ulD+9gEKULoAAQAtAbwA" +
  "hQLGAAUAABMnNTMVBz0QWBABvLpQULoAAQA+ACwEcgKaAAgAACUjAQEzASEVIQHkb/7JATZv/vADn/xjLAE3ATf+8E4AAAEAPgAsBsoCmgAIAAAlIwEBMwEhFSEB5G/+yQE2b/7wBff6CywBNwE3/v" +
  "BOAAABAD4ALAkiApoACAAAJSMBATMBIRUhAeRv/skBNm/+8AhP97MsATcBN/7wTgAAAQA+ACwGygKaAA0AACUBATMBIQEzAQEjASEBAXX+yQE2b/7wBWL+8G8BNv7JbwEP+qIBDywBNwE3/vABEP7J" +
  "/skBEP7wAAIALf+SA10CxgA8AEoAAAUGIyImJjU0PgIzMhYWFRQGBiMiJic1BgYjIiY1NDY2MzIWFxc3MwcGBhUUMzI2NTQmIyIGBhUUFjMyNycyNjY1NCYjIgYGFRQWAnhkenOjV0B3omJxqFwwVD" +
  "coOAkYVC1YXjVfQCxFEAEFSRABBTAzOp2SbqZdmY5wW70yPx82Pi09IDFEKlWicWaoe0NYoG1QekUqIwQkMWVRQ25BIxwDQNIWOBIubF6MlmKudIyYKJAxTSk1SC9NLjRGAAMAKP/wAlgC1gAfACsA" +
  "NQAABSImNTQ2NjcmJjU0NjMyFhUUBgcXNjUXBgYHFyMnBgYDNjY1NCYjIgYVFBYTMjY3JwYGFRQWAQRmdho9NSImXVFQVkRQoiRUASUdVWUlHWVOOS8oJCgsGS8zRBGwNi5DEGNbLkdCJS1ML01XUU" +
  "c5WzXPMmYIPHAjZy0cIQHCIz0mJCYqJh84/mUYEt4lRi8yPAAAAQAtAAAB+ALGAA8AACERIiYmNTQ2NjMzESMRIxEBFEVoOjppRORQRAEyMVs+Plsx/ToCev2GAAACADf/wAHuAtYAMQA/AAAFIiYm" +
  "JzcWFjMyNjU0JicmJjU0NyY1NDYzMhYXByYmIyIGFRQWFx4CFRQHFhYVFAYGAzI2NTQmJiMiBhUUFhYBHENkOQVXCEZARDVBT2ZXXlxyW1pxC1YISDkuPTVJTlolVCooNl0gLzcySyYoPB1HQC9RMw" +
  "YwOSgiHy4QFkY5VykpR0dTWlAGLjIoHh8jFBMsPC1PIRQ8LitDJgE4KyMhKRMuIBYrHAAAAwAt//QDDwLWABMAJwBFAAAFIi4CNTQ+AjMyHgIVFA4CJzI+AjU0LgIjIg4CFRQeAjciJiY1NDY2MzIW" +
  "FhcHJiYjIgYVFBYzMjY3Fw4CAZ5MhmY5OWaGTE2FZjk5ZoVNO2dQLS1QZzs7aE8tLU9oPztcNDRcOzJPMgROBjopN0ZGNyo9Bk4FM1EMOWaGTE2FZjk5ZoVNTIZmOVAtT2k8PGlPLS1PaTw8aU8tTD" +
  "ZhPj5fNidGLQUmMU0+Pk82KgUvSioAAAQALQCzAk4C1gATACMAMQA5AAAlIi4CNTQ+AjMyHgIVFA4CJzI2NjU0JiYjIgYGFRQWFicRMzIWFRQGBxcjJyMVNTMyNjU0IyMBPjljSyoqS2M5OWJLKipL" +
  "YjlAYDc3YEBAYTc3YS1jOkEiH00/RS4zHSA9M7MrS2M5OWNLKipLYzk5Y0srOTtjOztiOjpiOztjO0MBKjArHywIfHV1oxkVKgAAAgBcAWcDIgLGAAwAFAAAAREzExMzESMRAyMDESERIzUhFSMRAa" +
  "ZQbm9POl9KX/7scAEbbwFnAV/+3QEj/qEBBf77AQX++wEnODj+2QAAAgAsAZoBaALWAA8AGwAAEyImJjU0NjYzMhYWFRQGBicyNjU0JiMiBhUUFsorSCsrSCsrSCsrSCsjMTIiIjIyAZoqRy0tSCkp" +
  "SC0tRypKLyUmMDAmJS8AAAEAKAHiAKsCxgADAAATNzMHKC5VNwHi5OT//wAoAeIBJQLGACYBOAAAAAYBOHoAAAEAXP+SAKwC7gADAAAXETMRXFBuA1z8pAAAAgBc/5IArALuAAMABwAAExEzEQMRMx" +
  "FcUFBQAYsBY/6d/gcBY/6dAAEAXAAAAewCxgALAAAzESM1MzUzFTMVIxH8oKBQoKABxky0tEz+OgABAFwAAAHsAsYAEwAANzUzNSM1MzUzFTMVIxUzFSMVIzVcoKCgUKCgoKBQrEzOTLS0TM5MrKwA" +
  "AAIALP/0AgAC1gAbACIAABc3JiY1NDY2NzczBxYWFwcmJicDNjY3FwYGIwcDFBYXEwYG1AlSXzdkRAhGCEdcDFgHMiUhMkQJWA14WQiWMi4gPUMMZBWOalB5RwRdYAxcTAYpNgr+ewM8OQZYalwBcU" +
  "hgEgF9CWcAAAIALQBRAkMCZgAjADMAADcnNyYmNTQ2Nyc3FzY2MzIWFzcXBxYWFRQGBxcHJwYGIyImJzcyNjY1NCYmIyIGBhUUFhZlOF0SExQRXThdGTwhITwZXThdERQTEl04XBo8ISE8GncmQCcn" +
  "QCYnQCYmQFE3XRk8ISE9GV03XBETExFcN10ZPSEhPBldN1wSExMSISZAJydAJiZAJydAJgAAAwA3/6YCPgMgACMAKwAzAAAFNSYmJzcWFhc1LgI1NDY3NTMVFhYXByYmJxUWFhUUBgYHFQMUFhYXNQ" +
  "YGATQmJicVNjYBHWV5CFgJRz5QXilzZEpYZgtZBzcyeF82Yj/JFTczO0QBSBQ3NDxDWk0MgF8GQlEK+xQxRzRUbQRZXRB2UwYySQ7qIGVIOFUzBUsCXxwmHg7eBDz+exssJRHpBTcAAQA3AAACNALW" +
  "ACcAADM1NjY1NCYnIzUzJiY1NDY2MzIWFhcHJiYjIgYVFBYXMxUjFAYHIRU4OD0CAnJhDRA3YDxLYDQHZA1FLDlFDgyypi0/AZpSImM/CRQKSidEHzhZNDFQLwcyMUc4Fz0oSlltIFcAAf/6AAACRg" +
  "LGABgAADc1MzUnIzUzAzMTEzMDMxUjBxUzFSMVIzVYnQGcbsxmwMBmzKTSAdPTVo9ORQFOAVX+tAFM/qtOAUVOj48AAAEAKAA4AgYCFgALAAA3NSM1MzUzFTMVIxXwyMhOyMg4yE7IyE7IAAABACgB" +
  "AAHgAU4AAwAAEzUhFSgBuAEATk4AAAEAKABUAc4B+gALAAA3Nyc3FzcXBxcHJwconJw3nJw3nJw3nJyLnJw3nJw3nJw3nJwAAwAoADQB9AIaAAsADwAbAAABIiY1NDYzMhYVFAYFNSEVByImNTQ2Mz" +
  "IWFRQGAQ4eIiIeHiIi/vwBzOYeIiIeHiIiAZ4jGxsjIxsbI55OTswjGxsjIxsbIwAAAgAoAJ0B9AG5AAMABwAAEzUhFQU1IRUoAcz+NAHMAWtOTs5OTgABADIAIAH4AiIABgAANzUlJTUFFTIBg/59" +
  "AcYgVK2tVMxqAAABACgAIAHuAiIABgAAJSU1JRUFBQHu/joBxv59AYMgzGrMVK2tAAIAKAAAAfICNAALAA8AADc1IzUzNTMVMxUjFQU1IRXmvr5Ovr7+9AHKar5Ovr5OvmpKSgABACgA7AHjAa4AGA" +
  "AAJSImJy4CIyIVIzQ2MzIWFxYWMzI1MxQGAWAjKx4UFxELNk9IOiYtGhobEzVPSOwbJBkXBmtSZh4iIhNrUmYAAQAoAEIBzAE8AAUAACU1ITUhFQGC/qYBpEKwSvoAAQAoAX8BggKhAAYAABMTMxMj" +
  "JwcoeGp4UltbAX8BIv7e19cABQAs//gC9gLOAAsADwAbACcAMwAAEyImNTQ2MzIWFRQGAwEzARMyNjU0JiMiBhUUFgEiJjU0NjMyFhUUBicyNjU0JiMiBhUUFsZDV1dDRFZWlgHqUP4WAikpKSkoKi" +
  "oBvkNXV0NEVlZEKSkpKSgqKgFuW1VWWlpWVVv+kgLG/ToBrDw2Njw8NjY8/kxbVVZaWlZVWz48NjY8PDY2PAAHACz/+ARmAs4ACwAPABsAJwAzAD8ASwAAEyImNTQ2MzIWFRQGAwEzARMyNjU0JiMi" +
  "BhUUFgEiJjU0NjMyFhUUBiEiJjU0NjMyFhUUBiUyNjU0JiMiBhUUFiEyNjU0JiMiBhUUFsZDV1dDRFZWlgHqUP4WAikpKSkoKioBvkNXV0NEVlYBLENXV0NEVlb+TCkpKSkoKioBmCkpKSkoKioBbl" +
  "tVVlpaVlVb/pICxv06Aaw8NjY8PDY2PP5MW1VWWlpWVVtbVVZaWlZVWz48NjY8PDY2PDw2Njw8NjY8AAABAC0AAAKbAsYACAAAIREBNQEBFQERATv+8gE3ATf+8gIv/vJvATb+yW8BDf3TAAABAC0A" +
  "LALzApoACAAAJQEhNSEBMwEBAU0BDf3TAi/+8m8BNv7JLAEOUgEO/sn+yQABAC0AAAKbAsYACAAAATMRARUBATUBATtSAQ7+yf7JAQ4Cxv3TAQ1v/skBNm/+8gABAC0ALALzApoACAAAJSMBATMBIR" +
  "UhAdNv/skBNm/+8gIv/dMsATcBN/7yUgAAAgAsAmUBMgLHAAMABwAAEzUzFTM1MxUsWFZYAmViYmJiAAEALAJlAIQCxwADAAATNTMVLFgCZWJiAAEALAJWAMwC1gADAAATJzMXhlpeQgJWgIAAAQAs" +
  "AlYAzALWAAMAABM3MwcsQl5aAlaAgAABADIBxwCkAsYAAwAAEzczBzIeVDQBx///AAEALAJWAT4C2wAGAAATNzMXIycHLFpeWkZDQwJWhYVZWQABACwCVgE+AtsABgAAEzMXNzMHIyxGQ0NGWl4C21" +
  "lZhQAAAQAsAlsBQwLbAA0AABMiJiczFhYzMjY3MwYGuD1MAzoFKyIjKgQ6A0oCW0Y6IiAgIjpGAAIALAJAAOQC+AALABcAABMiJjU0NjMyFhUUBicyNjU0JiMiBhUUFognNTUnJzU1JxIYGBISGBgC" +
  "QDUnJzU1Jyc1MhgSEhgYEhIYAAABACwCWwFnAtoAGAAAASImJyYmIyIGByM2NjMyFhcWMzI2NzMGBgEFEyIRERQPEhcCNAI1KBgjER4UExQDNAM0AmIPDQ4MGSQ6OxAOGBslOT8AAQAsAnEBOAK5AA" +
  "MAABM1IRUsAQwCcUhIAAABACwCWwCjAxYABgAAEzU3MwczFSw9OjckAltSaWFaAAEALP8QAKP/ywAGAAAXNyM1MxUHLDckZD3wYVpSaQAAAQAs/yQBEQAKABQAABciJic3FjMyNTQmIyc3MwcWFhUU" +
  "BqEwOgszES82HDAcJkAiMS8/3C0hFCooExkePC4CMScqNAABACz/LgDfABIAFAAAFyImNTQ2NzcXBwYGFRQWMzI3FwYGiSsyJRQeOSMTDBANHBQYCzHSJCIdPRwoEjAaHgwMDg44Cw8AAQB8ATwBqA" +
  "GAAAMAABM1IRV8ASwBPEREAAABABQCEwK8AmMAAwAAEzUhFRQCqAITUFAAAAEAKAEoAQ4B4gADAAATNTcVKOYBKEJ4QgAAAQAo//AB6QIeAAMAABcBMwEoAXlI/ocQAi790gAAAQB8ATUB5AGDAAMA" +
  "ABM1IRV8AWgBNU5OAAABACgBFwFcAgMAAwAAEzUlFSgBNAEXTKBMAAEAKP/wAnUC1gADAAAXATMBKAH5VP4HEALm/RoAAAIALAJlAQQCxwADAAcAABM1MxUzNTMVLFgoWAJlYmJiYv//ACwCZQEyAs" +
  "cABgFUAAD//wAsAlYAzALWAAYBVgAA//8ALAJWAMwC1gAGAVcAAP//ACwCcQE4ArkABgFeAAD//wAs/yQBEQAKAAYBYQAAAAEAAAFwAHIAEABbAAUAAQAAAAAAAAAAAAAAAAAEAAEAAAAAABoAJgAy" +
  "AD4ASgBWAGIAbgB6AIYAqgDaAQoBFgEiAS4BOgFGAWEBbQF4AYMBmQGlAbEBvQHJAdUB4QHtAfkCDQJFAlECXQJpAnUCjAKXAqMCrwK7AscC0wLfAusC9wMDAw4DGgM6A0YDYANsA3sDhwOTA58Dqg" +
  "PEA9oD5gPyA/4ECgQrBFcEYwRvBHsEhwSXBKMErgS6BPoFFwU2BXUFpAWwBbwFyAYMBhgGJAYwBjwGTQZYBmQGbwaQBpwGqAa0BsAGzAbcBugG9AcABwwHIAc8B0gHYwd4B4QHkAecB7IHvgfKB9YI" +
  "FggiCC0IOAhDCE4IWQhlCHEIfAjaCQoJNglCCU0JWAljCW8JnwmrCbcJ+QorCjcKQgpNClgKZApvCnoKyQrmCyYLMQs8C0gLVAtzC38LiwuWC6ILrQu4C8MLzgvZC+cL8gwFDBAMJgwxDEkMVQxpDH" +
  "UMgQyMDJcMyQzrDPcNAg0ODRkNRA1wDXwNhw2SDZ0NrQ24DcMNzg3aDgkOPA5sDoEOjA6XDqIO4A7sDvcPAg8ND0QPYg9tD5MPng+9D8kP1A/fD+oP9RAFEBAQHBAoEDMQRRBhEG0QhhClELEQvBDH" +
  "EN0Q6RD0EQARDBEcESgRNBF2EZwRvBHoEfsSKxJmEoEStBL0EwwTWBOYE6YTthPGE9YT6hQaFFUUbRRtFG0UhRSdFLUUwBTQFNwU6BT4FRQVMRVjFZcVoBW2FdYWBxYWFiQWMBY8FkgWVBZpFn4Wrh" +
  "beFu8XABcIFxQXLRc6F0oXUxduF3oXixecF7IXwRfYF+8YBhgpGI8Y4Rj9GVkZuxoNGjQaYBptGngahRqZGq0ayRsFG1QbpRveHAQcGBwlHD4caxx+HJAcoxy9HOMc8h0EHVMdwh3aHfIeCh4hHjIe" +
  "Ph5LHlgeZR52HoceoR7HHvAe/R8NHx0fPx9iH28ffB+JH5gfpR+yH8Ef0h/aH+If6h/yH/oAAAABAAAAAczNtOmZFF8PPPUADwPoAAAAAOWpZlMAAAAA5cz4OP84/xAJIgQiAAAABgACAAAAAAAAAl" +
  "gAKAKcABQCnAAUApwAFAKcABQCnAAUApwAFAKcABQCnAAUAp0AEwKcABQDzAAUAqgAXAK/AC0CvwAtAr8ALQK/AC0CvwAtAr8ALQK2AFwCtgBcArYAFAK2ABQCWwBcAlsAXAJbAFwCWwBcAlsAXAJb" +
  "AFwCWwBcAlsAXAJbAFwCTgBcArwALQK8AC0CvAAtArwALQK8AC0CyQBcAskAEQLJAFwBDgBcA08AXAEOAFwBDv/+AQ4ABAEOAFsBDgAOAQ4AAQEOACIBDv/pAlUAQwJVAEMCgABcAoAAXAJEAFwCRA" +
  "BcAkQAXAJEAFwCRAAUA20AXALnAFwC5wBcAucAXALnAFwC5wBcAucAXALjAC0C4wAtAuMALQLjAC0C4wAtAuMALQLjAC0C4wAtAuMALQRAAC0CigBcAmwAXALdAC0CoABcAqAAXAKgAFwCoABcAoAA" +
  "NwKAADcCgAA3AoAANwKAADcCKAAMAigADAIoAAwCKAAMArEATQKxAE0CsQBNArEATQKxAE0CsQBNArEATQKxAE0CsQBNArEATQKxAE0CmwAUA7EAJgOxACYCXgAPAkD/+gJA//oCQP/6AkD/+gIgAB" +
  "wCIAAcAiAAHAIgABwCJwAsAicALAInACwCJwAsAicALAInACwCJwAsAicALAInACwCJwAsA5cALAJTAFACIgAsAiIALAIiACwCIgAsAiIALAIiACwCUwAsApYALAJTACwCPQAsAjEALAIxACwCMQAs" +
  "AjEALAIxACwCMQAsAjEALAIxACwCMQAsAYsAPAJSACwCUgAsAlIALAJSACwCUgAsAkUAUAJFAAoCRf/xAPQATgD0AFAA9ABQAPT/8QD0AA4A9AABAPT/9AD0ABQA9P/cAe4ATgEE//sBBP/7AQT/+w" +
  "JOAFACTgBQAQsAUAELAFABPgBQAQsAUAELAAYDbQBQAkUAUAJFAFACRQBQAkUAUAJFAFACRQBQAj0ALAI9ACwCPQAsAj0ALAI9ACwCPQAsAj0ALAI9ACwCPQAsA74ALAJTAFACUwBQAlMALAF7AFAB" +
  "ewBQAXsAOwF7ADUCCAAsAggALAIIACwCCAAsAggALAJLAFABiAA3AYgANQGPADcBiAA3Aj8AUAI/AFACPwBQAj8AUAI/AFACPwBQAj8AUAI/AFACPwBQAj8AUAI/AFACGAAWAzMAFgMzABYCSQAvAh" +
  "kAFgIZABYCGQAWAhkAFgIZADMCGQAzAhkAMwIZADMCqwA8AlcAPAKCADwCtQA3AZEAKAGjACgCPwBQApcAMgGAACgCawA8AmUAMgJnAB4CcgA8AlEAMgIMABQCXAAoAlEAKACq/zgDIAAUAtwAFAMO" +
  "ABQA8gAUAVwAKAFMABQBSgAKAPoAAAD6AAAJYAA+BwgAPgSwAD4AyQAsAMkALAEpAFwBKQBcAjsALADVADIA1QAyAi8ALAIvACwAyQAsATgALAGuACwB3v/2AeAAKAHHACgBowAsAk8ALAOLACwCLQ" +
  "AsARIALQESAA8BhQAtAYUADwFbAFwBWwAPAMkALAFuACwBcAAtAXAALQDLAC0AywAtAhUALAIZACcBSwAsAUsALAFaAC0AsgAtBLAAPgcIAD4JYAA+BwgAPgOKAC0CbAAoAlQALQIlADcDPAAtAnsA" +
  "LQN+AFwBlAAsANMAKAFNACgBCABcAQgAXAJIAFwCSABcAiIALAJwAC0CdQA3AmMANwJA//oCLgAoAggAKAH2ACgCHAAoAhwAKAIgADICIAAoAhoAKAILACgB9AAoAaoAKAMiACwEkgAsAsgALQMgAC" +
  "0CyAAtAyAALQAAACwAAAAsAAAALAAAACwAAAAyAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAACwAAAAsAAAALAAAAHwAAAAUAAAAKAAAACgAAAB8AAAAKAAAACgAAAAsAV4ALAD4ACwA+AAs" +
  "AWQALAE9ACwAAQAAA+3+2QAACWD/OP1ECSID6AAAAAAAAAAAAAAAAAAAAXAABAJFAZAABQAAAooCWAAAAEsCigJYAAABXgAyAT4AAAAAAAAAAAAAAACAAAAHAAAAaAAAAAAAAAAAVlJDTADAACAiEg" +
  "Pt/tkAAARAAQYAAACTAAAAAAISAsYAAAAgAAoAAAACAAAAAwAAABQAAwABAAAAFAAEAzQAAAAuACAABAAOAC8AOQB+AKwBEwErATcBPgFIAU0BfiAUIBogHiAiICYgMCAzIDohIiGTIhL//wAAACAA" +
  "MAA6AKAArgEWAS4BOQFBAUoBUCATIBggHCAgICYgMCAyIDkhIiGQIhL//wAAAMAAAAAAAAAAAAAAAAAAAAAAAADhBAAAAAAAAODl4R/hBuDv4BQAAN8yAAEALgAAAEoA0gDqAbQB3gHwAfoCCAIOAA" +
  "ACaAJsAnAAAAAAAAAAAAAAAmoAAAAAAQIBDAEqARMBQAFOATEBKwEaARsBEgFDAQgBFgEHARQBCQEKAUkBRwFIAQ4BMAABAAwADQATABcAIAAhACYAKQAzADUANwA8AD0AQwBNAE8AUABUAFkAXQBo" +
  "AGkAawBsAHABHgEVAR8BTQEZAWwAdAB/AIAAhgCKAJMAlACZAJwApgCpAKsAsACxALcAwQDDAMQAyADOANIA3QDeAOAA4QDlARwBOgEdAUsBAwENAT4BQQE/AUIBOwEzAWsBNADtASYBTAE1AW4BNw" +
  "FKAP8BAAFtAO8BMgEQAW8A/gDuAScA/AD7AP0BDwAGAAIABAAKAAUACQALABAAHQAYABoAGwAvACsALAAtABYAQQBHAEQARQBLAEYBRQBKAGIAXgBgAGEAbQBOAM0AeQB1AHcAfQB4AHwAfgCDAJAA" +
  "iwCNAI4AoQCeAJ8AoACJALUAuwC4ALkAvwC6AUYAvgDXANMA1QDWAOIAwgDkAAcAegADAHYACAB7AA4AgQARAIQAEgCFAA8AggAUAIcAFQCIAB4AkQAcAI8AHwCSABkAjAAjAJYAIgCVACUAmAAkAJ" +
  "cAKACbACcAmgAyAKQAMACiADEAowAuAJ0AKgClADQAqAA2AKoAOACsADoArgA5AK0AOwCvAD4AsgBAALQAPwCzAEIAtgBJAL0ASAC8AEwAwABRAMUAUwDHAFIAxgBVAMkAWADMAFcAywBWAMoAXADR" +
  "AFsA0ABaAM8AZwDcAGQA2QBfANQAZgDbAGMA2ABlANoAagDfAG4A4wBvAHEA5gBzAOgAcgDnASQBJQEgASIBIwEhATwBPQERAVMBUAFRAVIAAAANAKIAAwABBAkAAACmAAAAAwABBAkAAQAKAKYAAw" +
  "ABBAkAAgAOALAAAwABBAkAAwAwAL4AAwABBAkABAAaAO4AAwABBAkABQBWAQgAAwABBAkABgAaAV4AAwABBAkACACQAXgAAwABBAkACQBgAggAAwABBAkACwAwAmgAAwABBAkADAAwAmgAAwABBAkA" +
  "DQEiApgAAwABBAkADgA2A7oAQwBvAHAAeQByAGkAZwBoAHQAIAAyADAAMgA0ACAAVABoAGUAIABHAGUAaQBzAHQAIABQAHIAbwBqAGUAYwB0ACAAQQB1AHQAaABvAHIAcwAgACgAaAB0AHQAcABzAD" +
  "oALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwB2AGUAcgBjAGUAbAAvAGcAZQBpAHMAdAAtAGYAbwBuAHQALgBnAGkAdAApAEcAZQBpAHMAdABSAGUAZwB1AGwAYQByADEALgA4ADAAMAA7AFYAUgBD" +
  "AEwAOwBHAGUAaQBzAHQALQBSAGUAZwB1AGwAYQByAEcAZQBpAHMAdAAgAFIAZQBnAHUAbABhAHIAVgBlAHIAcwBpAG8AbgAgADEALgA4ADAAMAA7ACAAdAB0AGYAYQB1AHQAbwBoAGkAbgB0ACAAKA" +
  "B2ADEALgA4AC4ANAAuADEANgAtAGUAYgA2ADQAKQBHAGUAaQBzAHQALQBSAGUAZwB1AGwAYQByAEIAYQBzAGUAbQBlAG4AdAAuAHMAdAB1AGQAaQBvACwAIABWAGUAcgBjAGUAbAAsACAAQQBuAGQA" +
  "cgDpAHMAIABCAHIAaQBnAGEAbgB0AGkALAAgAEcAdQBpAGQAbwAgAEYAZQByAHIAZQB5AHIAYQAsACAATQBhAHQAZQBvACAAWgBhAHIAYQBnAG8AegBhAEIAYQBzAGUAbQBlAG4AdAAuAHMAdAB1AG" +
  "QAaQBvACwAIABBAG4AZAByAOkAcwAgAEIAcgBpAGcAYQBuAHQAaQAsACAATQBhAHQAZQBvACAAWgBhAHIAYQBnAG8AegBhAGgAdAB0AHAAcwA6AC8ALwBiAGEAcwBlAG0AZQBuAHQALgBzAHQAdQBk" +
  "AGkAbwAvAFQAaABpAHMAIABGAG8AbgB0ACAAUwBvAGYAdAB3AGEAcgBlACAAaQBzACAAbABpAGMAZQBuAHMAZQBkACAAdQBuAGQAZQByACAAdABoAGUAIABTAEkATAAgAE8AcABlAG4AIABGAG8Abg" +
  "B0ACAATABpAGMAZQBuAHMAZQAsACAAVgBlAHIAcwBpAG8AbgAgADEALgAxAC4AIABUAGgAaQBzACAAbABpAGMAZQBuAHMAZQAgAGkAcwAgAGEAdgBhAGkAbABhAGIAbABlACAAdwBpAHQAaAAgAGEA" +
  "IABGAEEAUQAgAGEAdAA6ACAAaAB0AHQAcABzADoALwAvAG8AcABlAG4AZgBvAG4AdABsAGkAYwBlAG4AcwBlAC4AbwByAGcAaAB0AHQAcABzADoALwAvAG8AcABlAG4AZgBvAG4AdABsAGkAYwBlAG" +
  "4AcwBlAC4AbwByAGcAAAADAAAAAAAA/5wAMgAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAf//AA8AAQAAAAwAAABAAAAAAgAIAAEAHwABACEAiAABAIoApgABAKgA6AABAOkA7AACAT4BPgABAUABQAAB" +
  "AUIBQgABAAwABAAWAB4AJgAuAAIAAQDpAOwAAAABAAQAAQE/AAEABAABATcAAQAEAAEBQQABAAQAAQFcAAAAAQAAAAoAMABAAARERkxUABpjeXJsABpncmVrABpsYXRuABoABAAAAAD//wABAAAAAW" +
  "tlcm4ACAAAAAIAAQAAAAIABhxsAAIACAACAAoBcgABAEoABAAAACAAqgCOAKoAqgCqAKoAqgCqAKoAqgCqAJgAqgCwALAAsACwALwAwgC8ALYAtgC2ALYAvADCAMgA+gEMASYBOAFWAAEAIAALAAwA" +
  "FwAYABkAGgAbABwAHQAeAB8AIABMAFkAWgBbAFwAhwCTAK0AxADFAMYAxwDQAOkBDQEcAR4BJgEnAT4AAgAX/+0Azv/sAAQAk//2AOn/9gDq//YA6//2AAEAPf/2AAEBHwAUAAEBJv/YAAEBIwAeAA" +
  "EBHwAKAAwAaP/YAGn/2ABq/9gAk//2AM7/8QDP//EA0P/xANH/8QDp//YA6v/2AOv/9gDs//EABABZAAoAWgAKAFsACgBcAAoABgBZABQAWgAUAFsAFABcABQApgAeAKgAHgAEAFn/xABa/8QAW//E" +
  "AFz/xAAHAFn/xABa/8QAW//EAFz/xABo/84Aaf/OAGr/zgAEAFn/7ABa/+wAW//sAFz/7AACFmgABAAAFswY8gA3ADQAAP/2//YAAAAE//b/9v/2AAD/5wAAAAD/zv/O/7r/4gAA/+z/4v/O//b/+w" +
  "AA/+gAAAAAAAAAAAAAAAD/7P/Y//YAAAAA//YAAAAA/+z/zgAAAAAAAAAAAAAAAAAAAAD/ugAAAAAAAAAA//H/9gAAAAAAAAAAAAAAAP/sAAAAAP/s/+z/xP/kAAAAAP/p//EAAgAAAAD/9gAAAAAA" +
  "AAAAAAAAAAAA/+wAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAAAAAAAAAP/EAAAAAAAAAAD/7P/2//L/9gAG//b/7AAP//YAAAAA/+z/7P/Y/9gAAP/2/9H/zv/2//b//v/2/+wAAAAAAAAAAAAAAA" +
  "D/9gAAAAAAAP/2AAAAAAAA/+z/8gAAAAAAAAAAAAAAAAAA/9gAAAAAAAAAAAAMAA4AAAAKAAD/4gAAAAD/8QAA//b/4v/Y/9j/6P/s/+L/9v/s/+wAAP/2AAD/9P/2AAAAAAAAAAD/9v/sAAAAAAAA" +
  "/+L/9gAA//b/4gAAAAAAAAAAAAAAAAAA/+z/2AAA//b/9gAA//r/9AAA//b/7AAA//EAAP/eAAAAAP/s/9j/2P/YAAD/9v/e/87/4v/xAAD/7AAAAAAAAAAAAAAAAP/s/+wAAAAAAAAAAAAAAAD/7P" +
  "/sAAAAAAAAAAAAAAAAAAAAAP/YAAAAAAAAAAD/+P/6AAAAAP/8AAD/9gAA/+gAAAAAAAAAAAAA/84AFAAA//L/5gAE//YAAP/4AAAAAAAAAAAAAAAA/+z/7AAAAAAAAAAAAAAAAP/sAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAP/s/+7/4gAA/+wAAP/s//D/xAAA//H/lv+6/6b/xAAAAAD/2P/iAAD/7P/2//b/4P/sAAD/9gAAAAD/uv/O/84AAAAAAAAAAAAA/7r/lv/iAAAAAAAAAAAAAAAAAA" +
  "D/pv/iAAD/8QAA//b/7AAA//gAAAAAAAAAAP/sAAAAAAAP/+wAAP/YAAAAAP/i/+L/9gAAAAAAAAAA//YAAAAAAAAAAAAA/+wAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAD/9v/m//H/6v/o/87/7AAAAAAAAAAAAAAAAP/Y/+j/xAAA//b/0P/x//YAAP/q/9j/7AAAAAAAAAAAAAAAAAAAAAAAAP/OAAAAAAAAAAD/8QAAAAAAAP/2AAAAAAAA/9gAAAAAAAAAAAAP//oAAA" +
  "AAAAD/8AAAAAD/7AAAAAAAAP/sAAD/7AAA/+z/7P/i//oAAAAA/+z/4gAAAAAAAAAAAAAAAAAAAAAAAAAA//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAwAAAAAAAAA" +
  "AP/8AAAAAP/i/+z/7P/2AAD/9v/2//YAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/iAAAAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "D/7P/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/q/9j/4v/U/+L/lv/OAAD/2AAA//H/9gAAAAD/2P+w" +
  "//b/zv/E/9j/4v/2/97/sP/i/+z/4v/O/+wAAP/iAAAAAAAA/5YAAP/oAAD/9v/i/+z/9v+wAAD/7P/sAAAAAP/Y/9j/8QAA//j//v/2//j/9v/u//QAAP/iAAAAAP/i/9j/2AAAAAAAAP/s/9j/9v" +
  "/2AAD/7AAA/+wAAAAAAAAAAAAA/+IAAAAAAAD/7gAAAAAAAP/i//YAAAAAAAAAAAAAAAAAAP/YAAAAAAAAAAD/9v/S/9j/9v/sAAD/4v/s/+IAAP/s//YAAP/8/84AAAAA/87/4v/2AAD/9gAA/+L/" +
  "7AAAAAAAAAAA//b/7AAAAAAAAAAAAAAAAP/2//b/2AAAAAAAAAAAAAAAAAAA//wAAAAA/+wAAP/s/7r/2P/E/8T/uv/E/+z/2P/sAAAAAAAUAAj/xAAAAAD/zv/E/9j/7P/2/7r/iAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAA/7r/7AAAAAAAAP/YAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAL/+AAA//z/+P/n//YAAP/2AAD/9v/s/+z/8f/2AAD/7P/s/+IAAP/2AAD/9gAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAD/5wAAAAAAAP/sAAAAAAAAAAAAAAAAAAAAAP/xAAAAAP/2AAD/4v+w/9j/uv/O/6b/ugAA/84AAP/Y//YACAAK/9j/nP/9/9j/xP/Y/+wAAP/O/4j/xAAAAAD/xP/EAAr/7AAKAAAABv+mAAD/4w" +
  "AK//b/2AAAAAD/4v/YAAAAAAAAAAoAAAAA/9gAAP/i/9gAAP/Y/9j/4v/sAAD/5wAAAAAAAAAA/9j/zv/EAAD/xP+6/9j/4gAA/+IAAP/OAAAAAAAAAAAAAAAAAAAAAAAA/+IAAAAAAAAAAAAAAAAA" +
  "AAAA/9gAAAAAAAD/2AAAAAAAAAAAAAD/9P/x//wAAP/2//YAAP/sAAD/8f/O/+z/7P/iAAAAAP/i/+z/+gAAAAAAAAAA//YAAAAAAAAAAAAA/+wAAAAAAAD/9gAAAAAAAP/O//EAAAAAAAAAAAAAAA" +
  "AAAP/sAAAAAP/xAAD/zv/O//b/1P/WAAD/7AAA/7oAAAAAAAAAAP/s/8v/7AAA/8T/2P/m/90AAP/iAAD/2AAA/+wAAAAA/+z/4gAAAAAAAAAAAAAAAP/sAAD/9gAAAAAAAP+6AAAAAAAA/+wAAAAA" +
  "AAAAAAAAAAD/7AAAAAAAAAAAAAD/2AAAAAD/sAAA/8QAAAAAAAD/3QAAAAr/9gAAAAD/9gAAAAAAAAAAAAD/2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/87/2f" +
  "/OAAAAAP/s/9j/zv+wAAD/4v9g/2D/dP+w//YAAP/E/87/7P/Y/+z/7P/E/+wAAP/sAAAAAP+I/7D/nAAAAAD/7AAAAAD/iP9g/84AAAAAAAAAAAAAAAAAAP90AAAAAP/iAAD//v/g/+z/9v/2/+z/" +
  "7AAA/+IAAAAA//b/9gAA/+IAAP/2/9j/2P/x//oAAP/s/+IAAAAAAAAAAAAAAAD/7AAAAAAAAP/sAAAAAAAA//b/7AAAAAAAAP/sAAAAAAAAAAAAAAAAAAAAAP/w//AAAP/2AAUACv/6AAD/9gAAAA" +
  "D/9gAAAAD/2AAZAAD/3v/i//YAAAAeAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAAAAD/9gAAAAAAAAAA/+IAAAAAAAAAAAAAAAAAAAAA//b/4gAA//H/7AAA/+wAAP/mAAAAAP/iAAAAAP/i" +
  "AAD/9v/s/87/7P/nAAD/8AAA/+wAAAAAAAAAAAAA//YAAAAAAAAAAAAAAAAAAP/iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAv/sAAD/9gAAAAAAAAAA//oAAAAAAAAAAAAA//YAAAAA//T/9P" +
  "/2//wAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/9gAAAAD/7AAAAAD/7AAAAAD/4gAA/8T/4gAA/+z/4v/YAAAAAAAA/+wA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9j/1AAA/+L/4v/ZAAAAAP/YAAAAAAAAAAAAAP/Y/8QAAP/I/9j/2P/sAAD/9gAA/+IAAAAAAA" +
  "AAAAAKAAAAAAAKAAD/2QAAAAAACgAAAAAAAAAAAAD/4gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7AAAAAAAAAAA/+z/5P/2/+r/9v+6/+IAAP/sAAAAAP/Y/9gAAAAA/5L/2AAA/9gAAAAA/+z/4v+w/+wAAP/2AAAAAAAA/+wAAAAAAAD/ugAAAAAAAP/Y//YA" +
  "AAAAAAD/4gAAAAAAAAAAAAAAAAAAAAD/7P/u/+IAAP/sAAD/7P/w/8QAAP/x/5b/uv+m/8QAAAAA/9j/4gAA/+z/9v/2/+AAAAAAAAAAAAAA/7oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP" +
  "/s//b/+wAA/+z/9gAAAAAAAP/xAAAAAP/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/" +
  "ugAAAAAAAAAAAAAAAAAAAAoAAP/YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/7oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAA/+z/7P/O/+L/4gAAAAAAAP/YAA" +
  "AAAP+cAAD/sP/OAAAAAP/OAAD/9gAAAAD/9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/2AAAAAAAA/84AAAAAAAAAAAAAAAAAAAAK" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAD/iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+z/4gAA/+z/4v+w/+IAAP/YAAD/4gAA/+wAAP/Y/7D/7P/i/87/4v/s/+z/" +
  "4v/E/+IAAAAAAAAAAAAA/+wAAAAAAAD/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9j/4v/iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9gAAAAAAAAAAAAAAAAAAAAA/+IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/0AAA/7wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+6AAAAAAAAAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAOAAAACgAA/+IAAAAA//EAAP/2/+L/2P/Y/+gAAP/i//b/7P/sAAD/9gAA//QAAAAAAAAAAAAA//YAAAAAAAAAAAAA//YAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAAAAAAD/zgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAD/9gAAAAAAAAAA/9gAAAAAAAD/9v/OAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/xAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//YAAAAA/8QAAAAAAA" +
  "AAAAAAAAAAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7AAAAAAAAAAAAAAAAAAA" +
  "/9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+r/2P/i/9T/4v+W/84AAP/YAAD/8f/2AAAAAP/YAAD/9v" +
  "/O/8T/2P/i//b/3v+wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+IAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/9gAAAAD/9gAAAAAAAAAAAAAAAAAA/+IAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACABAAAQCHAAAAiQCmAIcAqADMAKUAzgDuAMoA8AD5AOsBBwELAPUBDwEPAPoBEgESAPsBFAEWAPwBGgEa" +
  "AP8BIAEiAQABJAEkAQMBJgErAQQBMQExAQoBNAE0AQsBQgFNAQwAAgBbAAEACgAGAAsACwAHAAwADAANAA0AEgAQABMAEwADABQAFAAeABUAFQADABYAFgAeABcAHwAHACAAIAAoACEAJQAKACYAKQ" +
  "ACACoAKgAJACsAMgACADMANAAJADUANgAOADcAOAAWADkAOQApADoAOwAWADwAQgACAEMASwADAEwATAAHAE0ATQAfAE4ATwADAFAAUwATAFQAWAADAFkAXAARAF0AZwAJAGgAagAMAGsAawAOAGwA" +
  "bwAPAHAAcwAXAHQAfQAFAIYAhgACAIcAhwAaAJMAkwAcAJQAmAABAJkAmwAEAJwApgACAKgAqAACAKkAqgAUAKsArAAFAK0ArQAaAK4ArwAFALAAtgAEAMMAwwABAMQAxwASAM4AzwAYANAA0AAaAN" +
  "EA0QAYANIA3AABAN0A3wAIAOAA4AAUAOEA5AAIAOUA6AAZAOkA6QAcAOoA6gACAOsA6wAFAOwA7AAYAO0A7gAkAPAA8AAdAPEA8QAjAPIA8gA2APMA8wA1APQA9AAvAPUA9QAuAPYA9gAzAPcA9wAy" +
  "APgA+AAtAPkA+QAdAQcBCAAVAQkBCgAbAQsBCwAVAQ8BDwAlARIBEgArARQBFAA0ARUBFQAgARYBFgAwARoBGgAxASABIQAVASIBIgAnASQBJAAnASYBJgAhAScBJwAiASgBKAAhASkBKQAiASoBKw" +
  "AmATEBMQAqATQBNAAsAUIBQgAjAUMBTQALAAIAVQABAAsABgAMAAwAAQANABIAAwATABUAAQAWABYAAwAXACAAAQAhACUAAwAmADIAAQAzADQAGAA1ADkACwA6ADoAAQA7ADsAJAA8AEIAAQBDAEwA" +
  "AwBNAE4AAQBPAE8AAwBQAFMAAQBUAFgAAwBZAFwADgBdAGcACABoAGoADABrAGsAEQBsAG8ADQBwAHMAFgB0AH4ABAB/AH8AAQCAAJIAAgCTAJMAEgCUAJgAAgCZAKUAAQCmAKYAFACoAKgAFACpAK" +
  "oAAQCrAK8AFQCwALYABQC3AMAAAgDBAMEABQDCAMIAAQDDAMMAAgDEAMcABQDIAMwAAgDNAM0AAQDOANEADwDSANwABwDdAN8ACQDgAOAAEwDhAOQACQDlAOgAFwDpAOsAEgDsAOwADwDtAO4AHgDw" +
  "APAAGgDxAPEALgDyAPIAMgDzAPMAMQD0APQAKwD1APUAKgD2APYAGgD3APcAMAD4APgAKQD5APkALQEHAQgAEAEJAQoAGQELAQsAEAEMAQwAGwEOAQ4AHwESARIAJgEUARQAIwEVARUAJwEWARYALA" +
  "EbARsALwEgASEAEAEiASIAIQEjASMAIgEkASQAIQElASUAIgEmASYAHAEnAScAHQEoASgAHAEpASkAHQEqASsAIAExATEAJQE0ATQAKAFCAUIAMwFDAU0ACgACAAgAAgAKAHQAAQAaAAQAAAAIAC4A" +
  "NABCAEgATgBUAFoAZAABAAgA9AD3AQ0BHAEeASYBJwE+AAEBTv/sAAMBHQAeAR8AHgFOAAoAAQEV/9gAAQD3AAoAAQD3ABQAAQD3/8QAAgD3/8QBFf/OAAEA9//sAAIFGAAEAAAFcAYcABcAHAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/Y/7D/7AAAAAAAAAAAAAD/sAAA/8QAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAD/7AAAAAD/4v/2AAAAAP/sAAAAAAAAAAD/xAAAAAAAAAAAAAAAAAAKAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//YAAAAA//YAAP/YAAAAAAAAAAAAAP" +
  "/sAAD/9gAAAAD/zgAA/84AAAAAAAAAAP+6/5b/4gAAAAAAAAAAAAAAAAAA/6b/4gAA//EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA" +
  "AP/2AAAAAAAAAAAAAAAA/+z/7P/sAAAAAAAA//b/7AAA/+z/9gAA/9gAAP/sAAD/9v/xAAAAAAAAAAAAAAAAAAAAAAAA/9gAAAAAAAAAAAAA/5z/zgAAAAAAAAAAAAD/xAAA/7AAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAA/9gAAAAAAAD/zgAAAAAAAAAAAAAAAP/iAAAAAAAAAAAACgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/9AAAAAAAAAAAAAAAAAAAAAA/7wAAAAAAAAAAP/YAAAAAAAAAAAAAAAAAAAAAAAAAAD/ugAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAAAAAAA/+z/9g" +
  "AAAAAAAAAA/+wAAAAAAAAAAP/iAAD/9v/iAAAAAAAAAAAAAAAAAAD/7P/YAAD/9v/2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/7P/4/+wAAAAAAAAAAAAAAAD/" +
  "7AAAAAAAAAAAAAAAAAAAAAD/7AAAAAAAAAAAAAAAAAAAAAAAAAAA//b/zgAA//YAAAAAAAD/7P/2AAAAAAAAAAAAAP/2AAAAAAAAAAAAAAAAAAAAAAAAAAD/9gAA/+wAAP/i/+wAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACgAAAAD/7AAA/9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/x//gAAP/YAAAAAAAAAAAAAP/7//YAAAAA/5z/7AAA" +
  "AAAAAAAAAAAAAAAAAAAAAP/EAAAAAAAA//b/9gAA/8T/2AAAAAoAAAAUAAD/9gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/+wAAAAAAAAAAAAAAAAAAAAAAAD/7AAA/9gAAP/2AAAAAP+w/+L/7P" +
  "/i/87/7P/iAAAAAAAAAAD/lv/oAAD/9v/i/+z/9v+wAAD/7P/sAAAAAP/Y/9j/8QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/iAAAAAAAAAAAAAAAAAAAAAAAAAAD/+//sAAAAAAAAAAAAAAAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAA//YAAAAAAAD/9gAAAAD/2P/iAAD/9gAA/+L/7AAAAAAAAgAOAPAA+QAAAQcBCwAKAQ8BDwAPARIBEgAQARQBFgARARoBGgAUASABIQAVASMBIwAXASUBJgAYASgBKAAaAS" +
  "oBKwAbATEBMQAdATQBNAAeAUIBTQAfAAEA8ABTAAMABgAWABUADwAOABMAEgANAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAEAAgACAAEAAAAAAAAABwAAAAAACwAAABQABAAQAAAAAAAA" +
  "ABEAAAAAAAAAAAAAAAEAAQAAAAkAAAAJAAUAAAAFAAAACAAIAAAAAAAAAAAAAAAKAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgABAPAAUwADABYAGgAZABMAEgADABgAEQAVAAAAAA" +
  "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQABAAIAAgABAAQAAAAHAAgAAAAAAA4AAAAMAA8AFAAAAAAAAAAAABcAAAAAAAAAAAABAAEACgALAAoACwAFAAYABQAGAAkACQAAAAAAAAAAAAAADQAAAAAA" +
  "EAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABsAAQAAAAoAJAAyAAJERkxUAA5sYXRuAA4ABAAAAAD//wABAAAAAWxpZ2EACAAAAAEAAAABAAQABAAIAAEACAABAHwABAAOACgAMgBSAAMACAAOAB" +
  "QA6QACAJMA6gACAJwA6wACAKsAAQAEAOwAAgDOAAMACAASABoBBAAEARYBFgFIAQUAAwEWAUgBBgACAUgABAAKABQAHAAkAS4ABAEWARYBFgEvAAMBFgFIAS0AAwEWARYBLAACARYAAQAEAJMAzgEW" +
  "AUkAAA==";

const GLYPHS =
  "AAEAAAAQAQAABAAAR0RFRgAQABMAABK4AAAAFkdQT1NEdkx1AAAS0AAAACBHU1VCRHZMdQAAEvAAAAAgT1MvMoycPt0AAAGIAAAAYGNtYXDgiuCvAAACPAAAAFJnYXNwAAAAEAAAErAAAAAIZ2x5Zi" +
  "v877cAAAK8AAAKnmhlYWQwrt7SAAABDAAAADZoaGVhCZABZgAAAUQAAAAkaG10eD8OBIYAAAHoAAAAVGxvY2Ea6B33AAACkAAAACxtYXhwABoAUAAAAWgAAAAgbmFtZYJMqB4AAA1cAAAFNHBvc3T/" +
  "nwAyAAASkAAAACB2aGVhDdIOHQAAExAAAAAkdm10eAfvOvgAABM0AAAAUgABAAAAAgIM3ziJuV8PPPUAAwPoAAAAAOboTOIAAAAA5uhM4gAz/yIDkwL9AAAABgACAAAAAAAAAAEAAAXI/YoAAAPGAD" +
  "MAAAOTAAEAAAAAAAAAAAAAAAAAAAAVAAEAAAAVAE8ABAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAABAMBAZAABQAAAooCWAAAAEsCigJYAAABXgAyAUIAAAILBQIEBQQCAgQAAAAAAABAAAAAAAAAAAAA" +
  "R09PRwDA4ADgEgXI/YoAAAXIAnYAAAABAAAAAAIYA7EAAAAgAAICWABeA60AMwOiADMDrwAzA8YAMwIxADMDUgAzAqcAMwL7ADMDqgAzAmkAMwIGADMDLwAzAxYAMwJaADMDhwAzA2YAMwIGADMDZA" +
  "AzAlgAXwNmADMAAAABAAMAAQAAAAwABABGAAAABAAEAAEAAOAS//8AAOAA//8AAAABAAQAAAAUAAUACwARAAoABwAOAAIAEAAGAAMACAASAAkADwANAAQAAQAMAAAAAAAAADMAeADcAUEBewG4AeUC" +
  "SgKGAsADDwM6A10DmQPwBFUEkgUFBQUFTwACADMAYQN6AlsADQAbAAATJzcXNxc3FwcnBycHJwMnNxc3FzcXBycHJwcnUR71PLxAvF42P7xAvEC8HvU8vEC8XjY/vEC8QAGNOJJxdXV1riB0dHR0dP" +
  "5gOJJxdXV1riB0dHR0dAABADMAAANvAtUAMAAAIRE0JiMiBgYVFBYWMxUiJiY1NDY2MzIWFzY2MzIWFhUUBgYjNTI2NjU0JiYjIgYVEQGuUUksRigmQSg+YTc4ZkNKXBcXXUlDZTk3YD8pQSUoRS1J" +
  "UQHoVFwrSS8rRCg8Nl8+Q2Q5QkhIQjlkQz5fNjwoRCsvSipdU/4YAAAEADMAAAN8AsoAFgAiADkARQAAASImNTQ3NjMyFhYXFSYmIyIHFhYVFAYnMjY1NCYjIgYVFBYBIiYmJzUWFjMyNyYmNTQ2Mz" +
  "IWFRQHBicyNjU0JiMiBhUUFgECX3BlaOJElIw2WdloSycpOHBfO0dHOz1FRwEGSJyJLVnUbVAiKDlxXl9wZGUGPUVEPj1FRgE+YlFtNTcWJxlGKy0JB0w5UWJAPjU1Pj41NT7+ghkoFUYpLwkFTTpQ" +
  "Y2JRajc4Zj80ND8/NDQ/AAIAM/9AA5MCygA7AEcAAAU1MjY3JiY1ETQmJw4FFRUjETQmJyYmIzUyFhcVPgM3Mx4CFREUFzY2MzIWFRQGIyImJwYGJTI2NTQmIyIGBxYWAUVDaS4aEhYaDiYsKSMURg" +
  "YIDz0waWMBCSgyLQ1YEh8TEypSMUZUXVErRSgnjAFLMzsxKCZGIhJHwDdSXihmPAEULz4lDUBWYV5NGNABaz9aHDgyQJGhAyRgXkcMFT9CHf7dYyc7LUc+RU4ZIVVfuC8mHisvNhciAAACADMABwH+" +
  "Ar0AFQAnAAA3Iic1MjY2NTQmJiM1NjMyFhYVFAYGJzI+AjU0LgIjHgIVFAYGmjkuWINISIJZLjlpoFtboGhCclQvL1RyQkZoOTloBw0hTIhZWYhMIQ1XnGhmnVgeMldzQUJzVzEPW4RPToVaAAIAM/" +
  "++Ax8C/QAaACYAABc1NjY3ESYmJzUWMzI3FQYHERYWFxUmJiMiBjc2NjMyFhcRBiMiJzMhRCMqRBqi1NSiOk4jQyJbs2hltXIoVCwsVChSVlVTQj4NFAcCcwkUCz5CQj4ZEP2OBxQNPiMfH1AHBgYH" +
  "AlgMDAAAAQAzAAACdALCAB4AACE1ITUzMjY2NTQmIyIGFSM0NjYzMhYVFAYGBzMRMxECLv4KMFV7Q0k4N0pGMFo9XmkaOzT2RrpAPm1ES05LQjxcNXRfK1tRHgG8/UoAAgAz/yICyALKADcARwAABS" +
  "ImNTQ2NzY1NCYmIyIGFRQXHgIVFAYGIyImJjU0NjcmNTQ2NjMyFhYVFAYGBwYVFBYzMjcXBgEyNjY1NCYmIyIGBhUUFhYCa0JNHx07Lk8zS1sLL0gqM1Q0M1UzTD0MPnBKS3A9CyAeLSoiIRkYKv5Q" +
  "HjMeHjMeHTMfHjPeVEovcUOIfkRjNmRXKyYGNk8uM1UzM1UzPmURJy5Kc0NHgFcsW21IbEMoLA5BGAEwHjMeHjMeHzIeHjIfAAIAMwAAA3cCuAAjACcAADc1ISYmNTQ2NjMyFhYVFAYHIRUhNTY2NT" +
  "QmJiMiBgYVFBYXFQU1IRUzAQolLT5rQUFqPysnAQr+jTNCK0ovL0orQzL+jQND6UYdWyxAZz4+Z0ArWh9GTRFYNC9KKyxKLjVYEE3pRkYAAAIAMwAAAjYCFgAVACUAACEiJiY1NDY2MzIXNyc3FycH" +
  "FhUUBgYnMjY2NTQmJiMiBgYVFBYWAQM4Xzk5XzhCOl1PqAExXy04XzkrSCsrSCsrSCsrSDhfOThdOCloJxOpS2o3RzlfODIrSCsqRyoqRyorSCsAAgAz/8wB0wL5ACgAOAAAFzUjNTM1LgI1NDY3Ji" +
  "Y1MxQWFjMyNjY1MxQGBxYWFRQGBgcVMxUjFQMyNjY1NCYmIyIGBhUUFhbodnYzUjA8MTI7MitIKyxIKjI7MjI7MFE0dnYbK0grK0grK0grK0g0bC9YBzpZNThhGxxiOStIKytIKzpiGxtgOTRZOwdY" +
  "L2wBJCtIKypGKypGKypILAABADMAAAL8AvAAGwAAMzY3IzUzJiczFhczNjczBgczFSMWFyMmJyMGB1uBCrOzDIBKggrPDIBKggqzswuASYMJzwqCrqdArK+dvsKZra5AqK2ZvL6XAAEAMwAHAuMCtQ" +
  "ARAAA3JzcnNxcBITUhFxEjEQEXBydgLdqELYMBN/67AaQUQf7FhS2FBy7bgi2DATlAE/5dAUz+xIUthQABADMAAAInAvgAKwAAMxEjNTM1MxUzFSMVFAYHMzY2MzIWFRQHBhUUFhcjJiY1NDc2NTQm" +
  "IyIGFRF/TExGubkDAgYZWDdhWB4fGA5MDhUeHz4+T04CYDZiYjZbFiQQKCthWy9FRR8fRRYWSCAnRUggRDtjbP7+AAABADP/QQOHAsoAOwAABTcjIiYmNRE0JicOAwcRIxE0JicOAwcRIxE0JzMWFh" +
  "c+AjczFhYXPgI3MxYWFREUFhYzMycXAv8TLUlWJhAODignHQJGDhAOKCcdAkYtNQ4dDQklKhI7EiEGCSYtEjsiHRk4Li0TiL9JPIFpAWQkSRYMNUA5D/4yAgUlSiMMNUA5D/4yAg1HdhZFMBE0NREa" +
  "USASMzQSLloy/qBZZSpJaAACADP/8wMzAugANABEAAAFIi4CNTQ2NyYnLgIjNTIWFxYWFxYWFxYzMjY3NjY3NjY3NjYzFSIGBgcGBxYWFRQOAicyNjY1NCYmIyIGBhUUFhYBszVeRylFPEQhFyYyKi" +
  "1PHA4YChQyIyUqKUsZDRYJEjwoFCkUKTImFyJFPUUpR141M1QyMlQzMlUyMlUNKUdeNUZ3Iy1BLSwOPQodDiEUJkMODiIgESESJDwEAgM9DistQS4jd0Y2XkcoSjJVMjNUMjJUMzJVMgAAAgAzAAAB" +
  "0wKPABoAKgAAMzUjNTM1LgI1NDY2MzIWFhUUBgYHFTMVIxUDMjY2NTQmJiMiBgYVFBYW6HZ2M1IwOV84OV84MFE0b28bK0grK0grK0grK0hsL1gHOlo0OF04OF04M1o7B1gvbAEkK0grKkYrK0YqK0" +
  "grAAACADP/MQMxAsoARABOAAAFJicGBzU2NyY1ETQmJw4DBxEjETQmJw4DBxEjETQnMxYWFz4CNzMWFhc+AjczFhYVFTY2NzMWFhUUBgcWFhcnNjY1NCcOAgcCZygSTktLRAMQDg4oJx0CRg4QDign" +
  "HQJGLTUOHQ0JJSoSOxIhBgkmLRI7Ih0NMBQ6HSNkYAcgHkxARSAQKiMIzyBUKgxADCggIwHuJEkWDDVAOQ/+MgIFJUojDDVAOQ/+MgINR3YWRTARNDURGlEgEjM0Ei5aMlMaOhAie0ttvEQtSyPjOJ" +
  "dWc0IQOz0TAAMAM//hAzMC4QATACcAMwAABSIuAjU0PgIzMh4CFRQOAicyPgI1NC4CIyIOAhUUHgITIiY1NDYzMhYVFAYBs0+MaTw8aYxPUItpPDxpi1BFelw0NFx6RUV6XDQ0XHpFIC0tICAtLR88" +
  "aYxPUItpPDxpi1BPjGk8MTRcekVFelw0NFx6RUV6XDQBAi4fIC0tIB8uAAAAAAAADwC6AAMAAQQJAAAAnAAAAAMAAQQJAAEALgCcAAMAAQQJAAIADgDKAAMAAQQJAAMARADYAAMAAQQJAAQAMgEcAA" +
  "MAAQQJAAUAVAFOAAMAAQQJAAYALgGiAAMAAQQJAAcARAHQAAMAAQQJAAgAKgIUAAMAAQQJAAkAKAI+AAMAAQQJAAoAQgJmAAMAAQQJAAsAPgKoAAMAAQQJAAwAPALmAAMAAQQJAA0BIgMiAAMAAQQJ" +
  "AA4ANgREAEMAbwBwAHkAcgBpAGcAaAB0ACAAMgAwADIAMgAgAFQAaABlACAATgBvAHQAbwAgAFAAcgBvAGoAZQBjAHQAIABBAHUAdABoAG8AcgBzACAAKABoAHQAdABwAHMAOgAvAC8AZwBpAHQAaA" +
  "B1AGIALgBjAG8AbQAvAG4AbwB0AG8AZgBvAG4AdABzAC8AcwB5AG0AYgBvAGwAcwApAFIAZQB0AHIAbwBzAHAAZQBjAHQAIABDAGEAcgBkACAAUwB5AG0AYgBvAGwAcwBSAGUAZwB1AGwAYQByADIA" +
  "LgAwADAAMwA7AEcATwBPAEcAOwBOAG8AdABvAFMAYQBuAHMAUwB5AG0AYgBvAGwAcwAtAFIAZQBnAHUAbABhAHIATgBvAHQAbwAgAFMAYQBuAHMAIABTAHkAbQBiAG8AbABzACAAUgBlAGcAdQBsAG" +
  "EAcgBWAGUAcgBzAGkAbwBuACAAMgAuADAAMAAzADsAIAB0AHQAZgBhAHUAdABvAGgAaQBuAHQAIAAoAHYAMQAuADgALgA0AC4ANwAtADUAZAA1AGIAKQBOAG8AdABvAFMAYQBuAHMAUwB5AG0AYgBv" +
  "AGwAcwAtAFIAZQBnAHUAbABhAHIATgBvAHQAbwAgAGkAcwAgAGEAIAB0AHIAYQBkAGUAbQBhAHIAawAgAG8AZgAgAEcAbwBvAGcAbABlACAATABMAEMALgBNAG8AbgBvAHQAeQBwAGUAIABJAG0AYQ" +
  "BnAGkAbgBnACAASQBuAGMALgBNAG8AbgBvAHQAeQBwAGUAIABEAGUAcwBpAGcAbgAgAFQAZQBhAG0ARABlAHMAaQBnAG4AZQBkACAAYgB5ACAATQBvAG4AbwB0AHkAcABlACAAZABlAHMAaQBnAG4A" +
  "IAB0AGUAYQBtAC4AaAB0AHQAcAA6AC8ALwB3AHcAdwAuAGcAbwBvAGcAbABlAC4AYwBvAG0ALwBnAGUAdAAvAG4AbwB0AG8ALwBoAHQAdABwADoALwAvAHcAdwB3AC4AbQBvAG4AbwB0AHkAcABlAC" +
  "4AYwBvAG0ALwBzAHQAdQBkAGkAbwBUAGgAaQBzACAARgBvAG4AdAAgAFMAbwBmAHQAdwBhAHIAZQAgAGkAcwAgAGwAaQBjAGUAbgBzAGUAZAAgAHUAbgBkAGUAcgAgAHQAaABlACAAUwBJAEwAIABP" +
  "AHAAZQBuACAARgBvAG4AdAAgAEwAaQBjAGUAbgBzAGUALAAgAFYAZQByAHMAaQBvAG4AIAAxAC4AMQAuACAAVABoAGkAcwAgAGwAaQBjAGUAbgBzAGUAIABpAHMAIABhAHYAYQBpAGwAYQBiAGwAZQ" +
  "AgAHcAaQB0AGgAIABhACAARgBBAFEAIABhAHQAOgAgAGgAdAB0AHAAcwA6AC8ALwBzAGMAcgBpAHAAdABzAC4AcwBpAGwALgBvAHIAZwAvAE8ARgBMAGgAdAB0AHAAcwA6AC8ALwBzAGMAcgBpAHAA" +
  "dABzAC4AcwBpAGwALgBvAHIAZwAvAE8ARgBMAAMAAAAAAAD/nAAyAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAB//8ADwABAAAADAAAAAAAAAACAAEAAAASAAEAAAABAAAACgAcAB4AAURGTFQACAAEAA" +
  "AAAP//AAAAAAAAAAEAAAAKABwAHgABREZMVAAIAAQAAAAA//8AAAAAAAAAARAAAfT+DAPoBqMBTPlaBqYAAAABAAAAAAAAAAAAAAAAABQAAAL+AAADbQAAAvMAAAL+AAAC/gAAAwsAAALLAAADBgAA" +
  "Av4AAAMQAAADsgAAAs8AAALYAAADEwAAAtAAAAL+AAAC4AAAAzkAAAL+BqMBYwFMAAA=";

export const CARD_TEXT = "Retrospect Text";
export const CARD_SYMBOLS = "Retrospect Card Symbols";

/** The fonts, decoded once a process. */
let decoded: { text: Buffer; glyphs: Buffer } | null = null;
export function cardFontBytes() {
  decoded ??= { text: Buffer.from(TEXT, "base64"), glyphs: Buffer.from(GLYPHS, "base64") };
  return decoded;
}

export const cardFonts = () => {
  const f = cardFontBytes();
  return [
    { name: CARD_TEXT, data: f.text, weight: 400 as const, style: "normal" as const },
    { name: CARD_SYMBOLS, data: f.glyphs, weight: 400 as const, style: "normal" as const },
  ];
};
