// Retrospect: each IANA zone's principal city, for the wild nights' eclipse
// ranking (spec 7.5). Reads the committed tzdata 2026b tables at
// src/data/tz/ (zone1970.tab and backward, from github.com/eggert/tz at tag
// 2026b) and writes src/data/tz/cities.json, which the server reads.
// `src/lib/sky/visibility.test.ts` checks the JSON still matches the tables.
//
// Usage: node scripts/zone-cities.mjs   (Node 23.6 or later: it imports the .ts module directly)

import { readFileSync, writeFileSync } from 'node:fs';
import { parseLinks, parseZoneTab } from '../src/lib/sky/tzTables.ts';

const DIR = 'src/data/tz';
const cities = parseZoneTab(readFileSync(`${DIR}/zone1970.tab`, 'utf8'));
const links = parseLinks(readFileSync(`${DIR}/backward`, 'utf8'));
const out = {
  about:
    "Each zone's principal city from zone1970.tab, and backward's old and merged names, from tzdata 2026b (github.com/eggert/tz at tag 2026b). Generated by scripts/zone-cities.mjs; only the wild nights' eclipse ranking reads it, and no copy names a city.",
  cities,
  links,
};
// One entry a line, so a new tzdata release diffs readably.
const lines = (o) => Object.entries(o).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)}`).join(',\n');
writeFileSync(
  `${DIR}/cities.json`,
  `{\n "about": ${JSON.stringify(out.about)},\n "cities": {\n${lines(out.cities)}\n },\n "links": {\n${lines(out.links)}\n }\n}\n`,
);
console.error(`${Object.keys(cities).length} zones, ${Object.keys(links).length} links`);
